tbEquip_jinwu = 
{
	[1] = 
	{
		{szName="§»ng Long Bå §Ò Ch©u Liªn",tbProp={0,2975,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai PhËt Ch©u",tbProp={0,2985,},nQuality=1,},
		{szName="§»ng Long V« L­îng H¹ng Liªn",tbProp={0,2995,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn H¹ng Liªn",tbProp={0,3005,},nQuality=1,},
		{szName="§»ng Long T~ch §~a H¹ng Liªn",tbProp={0,3015,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn H¹ng Liªn",tbProp={0,3025,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Ch©u Liªn",tbProp={0,3035,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch Ch©u Liªn",tbProp={0,3045,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Ch©u Liªn",tbProp={0,3055,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Ch©u Liªn",tbProp={0,3065,},nQuality=1,},
		{szName="§»ng Long V¹n §éc H¹ng Liªn",tbProp={0,3075,},nQuality=1,},
		{szName="§»ng Long V¹n Linh H¹ng Liªn",tbProp={0,3085,},nQuality=1,},
		{szName="§»ng Long Hçn §én H¹ng Liªn",tbProp={0,3095,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn H¹ng Liªn",tbProp={0,3105,},nQuality=1,},
		{szName="§»ng Long Phong B¹o H¹ng Liªn",tbProp={0,3115,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh H¹ng Liªn",tbProp={0,3125,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa H¹ng Liªn",tbProp={0,3135,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng H¹ng Khuyªn",tbProp={0,3145,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn H¹ng Liªn",tbProp={0,3155,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Phï",tbProp={0,3165,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Phï",tbProp={0,3175,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn H¹ng Liªn",tbProp={0,3185,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Phï",tbProp={0,3195,},nQuality=1,},
		{szName="§»ng Long Tè Du H¹ng Liªn",tbProp={0,4813,},nQuality=1,},
		{szName="§»ng Long Y Thñy H¹ng Liªn",tbProp={0,4823,},nQuality=1,},

	},
	[2] = 
	{
		{szName="§»ng Long Bå §Ò T¨ng M¹o",tbProp={0,2976,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai T¨ng M¹o",tbProp={0,2986,},nQuality=1,},
		{szName="§»ng Long V« L­îng T¨ng M¹o",tbProp={0,2996,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Kh«i",tbProp={0,3006,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Kh«i",tbProp={0,3016,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Kh«i",tbProp={0,3026,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Ph¸t §¸i",tbProp={0,3036,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch Ph¸t §¸i",tbProp={0,3046,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Tr©m",tbProp={0,3056,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Tr©m",tbProp={0,3066,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Ph¸t §¸i",tbProp={0,3076,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Ph¸t §¸i",tbProp={0,3086,},nQuality=1,},
		{szName="§»ng Long Hçn §én Qu¸n",tbProp={0,3096,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Qu¸n",tbProp={0,3106,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Ph¸t Qu¸n",tbProp={0,3116,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh §Çu Hoµn",tbProp={0,3126,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa §Çu Hoµn",tbProp={0,3136,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Kh«i",tbProp={0,3146,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Qu¸n MiÖn",tbProp={0,3156,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Qu¸n",tbProp={0,3166,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Qu¸n",tbProp={0,3176,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn §¹o Qu¸n",tbProp={0,3186,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung §¹o Qu¸n",tbProp={0,3196,},nQuality=1,},
		{szName="§»ng Long Tè Du Qu¸n",tbProp={0,4814,},nQuality=1,},
		{szName="§»ng Long Y Thñy Qu¸n",tbProp={0,4824,},nQuality=1,},
	},
	[3] = 
	{
		{szName="§»ng Long Bå §Ò Kim ThiÒn ChØ Hoµn",tbProp={0,2977,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai §¹i To ChØ Hoµn",tbProp={0,2987,},nQuality=1,},
		{szName="§»ng Long V« L­îng §¹i Thoa ChØ Hoµn",tbProp={0,2997,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Nh­ u ChØ Hoµn",tbProp={0,3007,},nQuality=1,},
		{szName="§»ng Long T~ch §~a ChØ Hoµn",tbProp={0,3017,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn ChØ Hoµn",tbProp={0,3027,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Minh Ch©u ChØ Hoµn",tbProp={0,3037,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch L­u Ly ChØ Hoµn",tbProp={0,3047,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh TuyOt Ngäc ChØ Hoµn",tbProp={0,3057,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Linh Lung ChØ Hoµn",tbProp={0,3067,},nQuality=1,},
		{szName="§»ng Long V¹n §éc HuyOt TrUch ChØ Hoµn",tbProp={0,3077,},nQuality=1,},
		{szName="§»ng Long V¹n Linh HuyÒn ¢m Giíi",tbProp={0,3087,},nQuality=1,},
		{szName="§»ng Long Hçn §én Phi Hoa ChØ Hoµn",tbProp={0,3097,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Linh Xµ ChØ Hoµn",tbProp={0,3107,},nQuality=1,},
		{szName="§»ng Long Phong B¹o NhiOp Ph¸ch ChØ Hoµn",tbProp={0,3117,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh V¹n Tr­îng ChØ Hoµn",tbProp={0,3127,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Lôc Long Bµn ChØ",tbProp={0,3137,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng LiÖt DiÖm Bµn ChØ",tbProp={0,3147,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Dung Nham ChØ Hoµn",tbProp={0,3157,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ VÜnh Sinh ChØ Hoµn",tbProp={0,3167,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn H»ng Cöu Ph¸p Giíi",tbProp={0,3177,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Trïng D­¬ng Giíi",tbProp={0,3187,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Linh Ngäc ChØ Hoµn",tbProp={0,3197,},nQuality=1,},
		{szName="§»ng Long Tè Du Th­îng Giíi",tbProp={0,4815,},nQuality=1,},
		{szName="§»ng Long Y Thñy Th­îng Giíi",tbProp={0,4825,},nQuality=1,},
	},
	[4] = 
	{
		{szName="§»ng Long Bå §Ò Hé UyÓn",tbProp={0,2978,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Hé UyÓn",tbProp={0,2988,},nQuality=1,},
		{szName="§»ng Long V« L­îng Hé UyÓn",tbProp={0,2998,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Thóc UyÓn",tbProp={0,3008,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Thóc UyÓn",tbProp={0,3018,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Thóc UyÓn",tbProp={0,3028,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn L­u V©n Tô",tbProp={0,3038,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch TuyOt ¶nh Tô",tbProp={0,3048,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh CÈm Tó Hé UyÓn",tbProp={0,3058,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Sinh Hoa Thñ Tr¹c",tbProp={0,3068,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Hé UyÓn",tbProp={0,3078,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Hé UyÓn",tbProp={0,3088,},nQuality=1,},
		{szName="§»ng Long Hçn §én Hé UyÓn",tbProp={0,3098,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Hé UyÓn",tbProp={0,3108,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Hé UyÓn",tbProp={0,3118,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Hé UyÓn",tbProp={0,3128,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Hé UyÓn",tbProp={0,3138,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Hé UyÓn",tbProp={0,3148,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Hé UyÓn",tbProp={0,3158,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Tô",tbProp={0,3168,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Tô",tbProp={0,3178,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Hé UyÓn",tbProp={0,3188,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Hé UyÓn",tbProp={0,3198,},nQuality=1,},
		{szName="§»ng Long Tè Du Hé UyÓn",tbProp={0,4816,},nQuality=1,},
		{szName="§»ng Long Y Thñy Hé UyÓn",tbProp={0,4826,},nQuality=1,},
	},
	[5] = 
	{
		{szName="§»ng Long Bå §Ò Yªu §¸i",tbProp={0,2979,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Yªu §¸i",tbProp={0,2989,},nQuality=1,},
		{szName="§»ng Long V« L­îng Yªu §¸i",tbProp={0,2999,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Yªu §¸i",tbProp={0,3009,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Yªu §¸i",tbProp={0,3019,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Yªu §¸i",tbProp={0,3029,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Ti §¸i",tbProp={0,3039,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch Ti §¸i",tbProp={0,3049,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Yªu §¸i",tbProp={0,3059,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Ti §¸i",tbProp={0,3069,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Yªu §¸i",tbProp={0,3079,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Yªu §¸i",tbProp={0,3089,},nQuality=1,},
		{szName="§»ng Long Hçn §én TriÒn Yªu",tbProp={0,3099,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Thóc Yªu",tbProp={0,3109,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Thóc Yªu",tbProp={0,3119,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Thóc Yªu",tbProp={0,3129,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Thóc Yªu",tbProp={0,3139,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Yªu §¸i",tbProp={0,3149,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Yªu §¸i",tbProp={0,3159,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Ph¸p §¸i",tbProp={0,3169,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Ph¸p §¸i",tbProp={0,3179,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Yªu §¸i",tbProp={0,3189,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Yªu §¸i",tbProp={0,3199,},nQuality=1,},
		{szName="§»ng Long Tè Du Yªu §¸i",tbProp={0,4817,},nQuality=1,},
		{szName="§»ng Long Y Thñy Yªu §¸i",tbProp={0,4827,},nQuality=1,},

	},
	[6] = 
	{
		{szName="§»ng Long Bå §Ò Cµ Sa",tbProp={0,2980,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Cµ Sa",tbProp={0,2990,},nQuality=1,},
		{szName="§»ng Long V« L­îng Cµ Sa",tbProp={0,3000,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Kh¶i",tbProp={0,3010,},nQuality=1,},
		{szName="§»ng Long TÞch §Þa Kh¶i",tbProp={0,3020,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Kh¶i",tbProp={0,3030,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Nghª Th­êng Vò Y",tbProp={0,3040,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch TuyÕt Tiªu Y",tbProp={0,3050,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Khëi La Sam",tbProp={0,3060,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Th¸i §iÖp Y",tbProp={0,3070,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Cæ Y",tbProp={0,3080,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Hé Gi¸p",tbProp={0,3090,},nQuality=1,},
		{szName="§»ng Long Hçn §én Gi¸p",tbProp={0,3100,},nQuality=1,},
		{szName="§»ng Long ThÝ ThÇn Gi¸p Y",tbProp={0,3110,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Gi¸p Y",tbProp={0,3120,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh C¸i Y",tbProp={0,3130,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa C¸i Y",tbProp={0,3140,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Gi¸p",tbProp={0,3150,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Gi¸p Y",tbProp={0,3160,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ §¹o Bµo",tbProp={0,3170,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn §¹o Bµo",tbProp={0,3180,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn §¹o Bµo",tbProp={0,3190,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung §¹o Bµo",tbProp={0,3200,},nQuality=1,},
		{szName="§»ng Long Tè Du Y",tbProp={0,4818,},nQuality=1,},
		{szName="§»ng Long Y Thñy Y",tbProp={0,4828,},nQuality=1,},

	},
	[7] = 
	{
		{szName="§»ng Long Bå §Ò TriÒn Thñ",tbProp={0,2981,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Ph¸p C«n",tbProp={0,2991,},nQuality=1,},
		{szName="§»ng Long V« L­îng Giíi §ao",tbProp={0,3001,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn ThÇn Chïy",tbProp={0,3011,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Th­¬ng",tbProp={0,3021,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn B¶o §ao",tbProp={0,3031,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn B¶o KiÕm",tbProp={0,3041,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch TriÒn Thñ",tbProp={0,3051,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh B¶o §ao",tbProp={0,3061,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Uyªn ¦¬ng §ao",tbProp={0,3071,},nQuality=1,},
		{szName="§»ng Long V¹n §éc TriÒn Thñ",tbProp={0,3081,},nQuality=1,},
		{szName="§»ng Long V¹n Linh HuyOt NhÉn",tbProp={0,3091,},nQuality=1,},
		{szName="§»ng Long Hçn §én Phi §ao",tbProp={0,3101,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Tô TiÔn",tbProp={0,3111,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Phi Tiªu",tbProp={0,3121,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh TriÒn Thñ",tbProp={0,3131,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Tr­îng",tbProp={0,3141,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Th­¬ng",tbProp={0,3151,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn B¶o §ao",tbProp={0,3161,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ ThÇn KiÕm",tbProp={0,3171,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn ThÇn KiÕm",tbProp={0,3181,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn B¶o §ao",tbProp={0,3191,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung ThÇn KiÕm",tbProp={0,3201,},nQuality=1,},
		{szName="§»ng Long Tè Du KiÕm",tbProp={0,4819,},nQuality=1,},
		{szName="§»ng Long Y Thñy KiÕm",tbProp={0,4829,},nQuality=1,},
	},
	[8] = 
	{
		{szName="§»ng Long Bå §Ò T¨ng Hµi",tbProp={0,2982,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai T¨ng Hµi",tbProp={0,2992,},nQuality=1,},
		{szName="§»ng Long V« L­îng T¨ng Hµi",tbProp={0,3002,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Ngoa",tbProp={0,3012,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Ngoa",tbProp={0,3022,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Ngoa",tbProp={0,3032,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Lu",tbProp={0,3042,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch Ngoa",tbProp={0,3052,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Ngoa",tbProp={0,3062,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Ngoa",tbProp={0,3072,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Ngoa",tbProp={0,3082,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Ngoa",tbProp={0,3092,},nQuality=1,},
		{szName="§»ng Long Hçn §én Lu",tbProp={0,3102,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Lu",tbProp={0,3112,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Lu",tbProp={0,3122,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Ngoa",tbProp={0,3132,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Ngoa",tbProp={0,3142,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Ngoa",tbProp={0,3152,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Ngoa",tbProp={0,3162,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Lu",tbProp={0,3172,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Lu",tbProp={0,3182,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Ngoa",tbProp={0,3192,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Ngoa",tbProp={0,3202,},nQuality=1,},
		{szName="§»ng Long Tè Du Hµi",tbProp={0,4820,},nQuality=1,},
		{szName="§»ng Long Y Thñy Hµi",tbProp={0,4830,},nQuality=1,},
	},
	[9] = 
	{
		{szName="§»ng Long Bå §Ò Yªu Trôy",tbProp={0,2983,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Yªu Trôy",tbProp={0,2993,},nQuality=1,},
		{szName="§»ng Long V« L­îng Yªu Trôy",tbProp={0,3003,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Qua Chïy",tbProp={0,3013,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Yªu Trôy",tbProp={0,3023,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Yªu Trôy",tbProp={0,3033,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn H­¬ng Nang",tbProp={0,3043,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch H­¬ng Nang",tbProp={0,3053,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh H­¬ng Nang",tbProp={0,3063,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng H­¬ng Nang",tbProp={0,3073,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Yªu Trôy",tbProp={0,3083,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Yªu Trôy",tbProp={0,3093,},nQuality=1,},
		{szName="§»ng Long Hçn §én Béi",tbProp={0,3103,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Yªu Trôy",tbProp={0,3113,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Yªu Trôy",tbProp={0,3123,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Yªu Trôy",tbProp={0,3133,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Yªu Trôy",tbProp={0,3143,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Béi",tbProp={0,3153,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Béi",tbProp={0,3163,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Ngäc Béi",tbProp={0,3173,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Ngäc Béi",tbProp={0,3183,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Béi",tbProp={0,3193,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Béi",tbProp={0,3203,},nQuality=1,},
		{szName="§»ng Long Tè Du H­¬ng Nang",tbProp={0,4821,},nQuality=1,},
		{szName="§»ng Long Y Thñy H­¬ng Nang",tbProp={0,4831,},nQuality=1,},
	},
	[10] = 
	{
		{szName="§»ng Long Bå §Ò HuyÒn Trang ChØ Hoµn",tbProp={0,2984,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai §¹i Bi ChØ Hoµn",tbProp={0,2994,},nQuality=1,},
		{szName="§»ng Long V« L­îng Tiªu Thoa ChØ Hoµn",tbProp={0,3004,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn T~ch Tµ ChØ Hoµn",tbProp={0,3014,},nQuality=1,},
		{szName="§»ng Long T~ch §~a TrÇm H­¬ng ChØ Hoµn",tbProp={0,3024,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Phông Tinh ChØ Hoµn",tbProp={0,3034,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn BUch Ngäc ChØ Hoµn",tbProp={0,3044,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch B¨ng Tinh ChØ Hoµn",tbProp={0,3054,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh MÆc Ngäc ChØ Hoµn",tbProp={0,3064,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng San H« ChØ Hoµn",tbProp={0,3074,},nQuality=1,},
		{szName="§»ng Long V¹n §éc C« L©u ChØ Hoµn",tbProp={0,3084,},nQuality=1,},
		{szName="§»ng Long V¹n Linh HuyÒn U Giíi",tbProp={0,3094,},nQuality=1,},
		{szName="§»ng Long Hçn §én TrUch DiÖp ChØ Hoµn",tbProp={0,3104,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Kim ThiÒm ChØ Hoµn",tbProp={0,3114,},nQuality=1,},
		{szName="§»ng Long Phong B¹o §o¹t Hån ChØ Hoµn",tbProp={0,3124,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Thiªn Lu ChØ Hoµn",tbProp={0,3134,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Linh Ngäc Bµn ChØ",tbProp={0,3144,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng HuyOt Thó Bµn ChØ",tbProp={0,3154,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn D­¬ng Viªm ChØ Hoµn",tbProp={0,3164,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ §¹o Hµnh ChØ Hoµn",tbProp={0,3174,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn BÊt DiÖt Ph¸p Giíi",tbProp={0,3184,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Cµn Kh«n Giíi",tbProp={0,3194,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung D­¬ng Chi ChØ Hoµn",tbProp={0,3204,},nQuality=1,},
		{szName="§»ng Long Tè Du H¹ Giíi",tbProp={0,4822,},nQuality=1,},
		{szName="§»ng Long Y Thñy H¹ Giíi",tbProp={0,4832,},nQuality=1,},
	},
}


tbRepresentName = 
{
	[1] = "QuyÒn ThiÕu L©m",
	[2] = "C«n ThiÕu L©m",
	[3] = "ThiÕu L©m ®ao",
	[4] = "Chïy Thiªn V­¬ng",
	[5] = "Th­¬ng Thiªn V­¬ng",
	[6] = "§ao Thiªn V­¬ng",
	[7] = "Nga Mi kiÕm",
	[8] = "Nga Mi ch­ëng",
	[9] = "Thóy Yªn ®ao",
	[10] = "ThiÕu Yªn néi",
	[11] = "Ngò §éc ch­ëng",
	[12] = "Ngò §éc ®ao",
	[13] = "§­êng M«n phi ®ao",
	[14] = "§­êng M«n ná",
	[15] = "§­êng M«n tiÓu",
	[16] = "C¸i Bang ch­ëng",
	[17] = "C¸i Bang c«n",
	[18] = "Thiªn NhÉn chiÕn",
	[19] = "Thiªn NhÉn ma",
	[20] = "Vâ §ang khÝ",
	[21] = "Vâ §ang kiÕm",
	[22] = "§ao C«n L«n",
	[23] = "KiÕm C«n L«n",
}