tbEquip_BaiHu = 
{
	[1] = 
	{
		{szName="Nguy÷t Khuy’t Tr‰ng KiOp Ch©u Li™n",tbProp={0,5670,},nQuality=1,},
		{szName="Nguy÷t Khuy’t S∏t KiOp PhÀt Ch©u",tbProp={0,5680,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph∏ KiOp Hπng Li™n",tbProp={0,5690,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph n VÚ Hπng Li™n",tbProp={0,5700,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Y™n Hπng Li™n",tbProp={0,5710,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tr≠Íng Kh´ng Hπng Li™n",tbProp={0,5720,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Kinh HÂng Ch©u Li™n",tbProp={0,5730,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hi”u Nguy÷t Ch©u Li™n",tbProp={0,5740,},nQuality=1,},
		{szName="Nguy÷t Khuy’t T≠¨ng T≠ Ch©u Li™n",tbProp={0,5750,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Nguy÷t Ch©u Li™n",tbProp={0,5760,},nQuality=1,},
		{szName="Nguy÷t Khuy’t B∏ch ßÈc Hπng Li™n",tbProp={0,5770,},nQuality=1,},
		{szName="Nguy÷t Khuy’t U Minh Hπng Li™n",tbProp={0,5780,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Th´i M÷nh Hπng Li™n",tbProp={0,5790,},nQuality=1,},
		{szName="Nguy÷t Khuy’t BU ßÈc Hπng Li™n",tbProp={0,5800,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Mπn ßÂ Hπng Li™n",tbProp={0,5810,},nQuality=1,},
		{szName="Nguy÷t Khuy’t XUch Long Hπng Li™n",tbProp={0,5820,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hµo Ki÷t Hπng Li™n",tbProp={0,5830,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tham Lang Hπng Quy”n",tbProp={0,5840,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Li÷t D≠¨ng Hπng Li™n",tbProp={0,5850,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Linh ßÈng PhÔ",tbProp={0,5860,},nQuality=1,},
		{szName="Nguy÷t Khuy’t ∂o ∂nh PhÔ",tbProp={0,5870,},nQuality=1,},
		{szName="Nguy÷t Khuy’t L®ng Phong Hπng Li™n",tbProp={0,5880,},nQuality=1,},
		{szName="Nguy÷t Khuy’t MÈc VÚ PhÔ",tbProp={0,5890,},nQuality=1,},
		{szName="Nguy÷t Khuy’t DÀt ∂nh Hπng Li™n",tbProp={0,5900,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Thanh Phong Hπng Li™n",tbProp={0,5910,},nQuality=1,},

	},
	[2] = 
	{
		{szName="Nguy÷t Khuy’t Tr‰ng KiOp T®ng M∑o",tbProp={0,5671,},nQuality=1,},
		{szName="Nguy÷t Khuy’t S∏t KiOp T®ng M∑o",tbProp={0,5681,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph∏ KiOp T®ng M∑o",tbProp={0,5691,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph n VÚ Kh´i",tbProp={0,5701,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Y™n Kh´i",tbProp={0,5711,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tr≠Íng Kh´ng Kh´i",tbProp={0,5721,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Kinh HÂng Ph∏t ß∏i",tbProp={0,5731,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hi”u Nguy÷t Ph∏t ß∏i",tbProp={0,5741,},nQuality=1,},
		{szName="Nguy÷t Khuy’t T≠¨ng T≠ Tr©m",tbProp={0,5751,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Nguy÷t Tr©m",tbProp={0,5761,},nQuality=1,},
		{szName="Nguy÷t Khuy’t B∏ch ßÈc Ph∏t ß∏i",tbProp={0,5771,},nQuality=1,},
		{szName="Nguy÷t Khuy’t U Minh Ph∏t ß∏i",tbProp={0,5781,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Th´i M÷nh Qu∏n",tbProp={0,5791,},nQuality=1,},
		{szName="Nguy÷t Khuy’t BU ßÈc Qu∏n",tbProp={0,5801,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Mπn ßÂ Ph∏t Qu∏n",tbProp={0,5811,},nQuality=1,},
		{szName="Nguy÷t Khuy’t XUch Long ß«u Hoµn",tbProp={0,5821,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hµo Ki÷t ß«u Hoµn",tbProp={0,5831,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tham Lang Kh´i",tbProp={0,5841,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Li÷t D≠¨ng Qu∏n Mi÷n",tbProp={0,5851,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Linh ßÈng Qu∏n",tbProp={0,5861,},nQuality=1,},
		{szName="Nguy÷t Khuy’t ∂o ∂nh Qu∏n",tbProp={0,5871,},nQuality=1,},
		{szName="Nguy÷t Khuy’t L®ng Phong ßπo Qu∏n",tbProp={0,5881,},nQuality=1,},
		{szName="Nguy÷t Khuy’t MÈc VÚ ßπo Qu∏n",tbProp={0,5891,},nQuality=1,},
		{szName="Nguy÷t Khuy’t DÀt ∂nh Qu∏n",tbProp={0,5901,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Thanh Phong Qu∏n",tbProp={0,5911,},nQuality=1,},
	},
	[3] = 
	{
		{szName="Nguy÷t Khuy’t Tr‰ng KiOp Kim Thi“n Chÿ Hoµn",tbProp={0,5672,},nQuality=1,},
		{szName="Nguy÷t Khuy’t S∏t KiOp ßπi To Chÿ Hoµn",tbProp={0,5682,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph∏ KiOp ßπi Thoa Chÿ Hoµn",tbProp={0,5692,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph n VÚ Nh≠ u Chÿ Hoµn",tbProp={0,5702,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Y™n ßµn Y™n Chÿ Hoµn",tbProp={0,5712,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tr≠Íng Kh´ng Long ß∂m Chÿ Hoµn",tbProp={0,5722,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Kinh HÂng Minh Ch©u Chÿ Hoµn",tbProp={0,5732,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hi”u Nguy÷t L≠u Li Chÿ Hoµn",tbProp={0,5742,},nQuality=1,},
		{szName="Nguy÷t Khuy’t T≠¨ng T≠ TuyOt Ng‰c Chÿ Hoµn",tbProp={0,5752,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Nguy÷t Lung Linh  Chÿ Hoµn",tbProp={0,5762,},nQuality=1,},
		{szName="Nguy÷t Khuy’t B∏ch ßÈc HuyOt TUch Chÿ Hoµn",tbProp={0,5772,},nQuality=1,},
		{szName="Nguy÷t Khuy’t U Minh Huy“n Minh GiÌi	",tbProp={0,5782,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Th´i M÷nh Phi Hoa Chÿ Hoµn",tbProp={0,5792,},nQuality=1,},
		{szName="Nguy÷t Khuy’t BU ßÈc Linh Xµ Chÿ Hoµn",tbProp={0,5802,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Mπn ßÂ NhiOp Ph∏ch Chÿ Hoµn",tbProp={0,5812,},nQuality=1,},
		{szName="Nguy÷t Khuy’t XUch Long Vπn Ch≠Îng Chÿ Hoµn",tbProp={0,5822,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hµo Ki÷t LÙc Long Ph∂n Chÿ",tbProp={0,5832,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tham Lang Li÷t Di‘m Ph∂n Chÿ",tbProp={0,5842,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Li÷t D≠¨ng Dung Nham Chÿ Hoµn",tbProp={0,5852,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Linh ßÈng V‹nh Sinh Chÿ Hoµn",tbProp={0,5862,},nQuality=1,},
		{szName="Nguy÷t Khuy’t ∂o ∂nh Hªng Cˆu Ph∏p GiÌi",tbProp={0,5872,},nQuality=1,},
		{szName="Nguy÷t Khuy’t L®ng Phong TrÔng D≠¨ng GiÌi",tbProp={0,5882,},nQuality=1,},
		{szName="Nguy÷t Khuy’t MÈc VÚ Linh Ng‰c Chÿ Hoµn",tbProp={0,5892,},nQuality=1,},
		{szName="Nguy÷t Khuy’t DÀt ∂nh Thi™n Th«n Chÿ Hoµn",tbProp={0,5902,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Thanh Phong ß~a Vi Chÿ Hoµn",tbProp={0,5912,},nQuality=1,},
	},
	[4] = 
	{
		{szName="Nguy÷t Khuy’t Tr‰ng KiOp HÈ Uy”n",tbProp={0,5673,},nQuality=1,},
		{szName="Nguy÷t Khuy’t S∏t KiOp HÈ Uy”n",tbProp={0,5683,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph∏ KiOp HÈ Uy”n",tbProp={0,5693,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph n VÚ ThÛc Uy”n",tbProp={0,5703,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Y™n ThÛc Uy”n",tbProp={0,5713,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tr≠Íng Kh´ng ThÛc Uy”n",tbProp={0,5723,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Kinh HÂng L≠u V©n TÙ",tbProp={0,5733,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hi”u Nguy÷t TuyOt ∂nh TÙ",tbProp={0,5743,},nQuality=1,},
		{szName="Nguy÷t Khuy’t T≠¨ng T≠ C»m TÛ HÈ Uy”n",tbProp={0,5753,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Nguy÷t Hoa Sinh ThÒ Trπc",tbProp={0,5763,},nQuality=1,},
		{szName="Nguy÷t Khuy’t B∏ch ßÈc HÈ Uy”n",tbProp={0,5773,},nQuality=1,},
		{szName="Nguy÷t Khuy’t U Minh HÈ Uy”n",tbProp={0,5783,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Th´i M÷nh HÈ Uy”n",tbProp={0,5793,},nQuality=1,},
		{szName="Nguy÷t Khuy’t BU ßÈc HÈ Uy”n",tbProp={0,5803,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Mπn ßÂ HÈ Uy”n",tbProp={0,5813,},nQuality=1,},
		{szName="Nguy÷t Khuy’t XUch Long HÈ Uy”n",tbProp={0,5823,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hµo Ki÷t HÈ Uy”n",tbProp={0,5833,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tham Lang HÈ Uy”n",tbProp={0,5843,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Li÷t D≠¨ng HÈ Uy”n",tbProp={0,5853,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Linh ßÈng TÙ",tbProp={0,5863,},nQuality=1,},
		{szName="Nguy÷t Khuy’t ∂o ∂nh TÙ",tbProp={0,5873,},nQuality=1,},
		{szName="Nguy÷t Khuy’t L®ng Phong HÈ Uy”n",tbProp={0,5883,},nQuality=1,},
		{szName="Nguy÷t Khuy’t MÈc VÚ HÈ Uy”n",tbProp={0,5893,},nQuality=1,},
		{szName="Nguy÷t Khuy’t DÀt ∂nh HÈ Uy”n",tbProp={0,5903,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Thanh Phong HÈ Uy”n",tbProp={0,5913,},nQuality=1,},
	},
	[5] = 
	{
		{szName="Nguy÷t Khuy’t Tr‰ng KiOp Y™u ß∏i",tbProp={0,5674,},nQuality=1,},
		{szName="Nguy÷t Khuy’t S∏t KiOp Y™u ß∏i",tbProp={0,5684,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph∏ KiOp Y™u ß∏i",tbProp={0,5694,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph n VÚ Y™u ß∏i",tbProp={0,5704,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Y™n Y™u ß∏i",tbProp={0,5714,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tr≠Íng Kh´ng Y™u ß∏i",tbProp={0,5724,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Kinh HÂng Ti ß∏i",tbProp={0,5734,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hi”u Nguy÷t Ti ß∏i",tbProp={0,5744,},nQuality=1,},
		{szName="Nguy÷t Khuy’t T≠¨ng T≠ Y™u ß∏i",tbProp={0,5754,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Nguy÷t Ti ß∏i",tbProp={0,5764,},nQuality=1,},
		{szName="Nguy÷t Khuy’t B∏ch ßÈc Y™u ß∏i",tbProp={0,5774,},nQuality=1,},
		{szName="Nguy÷t Khuy’t U Minh Y™u ß∏i",tbProp={0,5784,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Th´i M÷nh Tri“n Y™u",tbProp={0,5794,},nQuality=1,},
		{szName="Nguy÷t Khuy’t BU ßÈc ThÛc Y™u",tbProp={0,5804,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Mπn ßÂ ThÛc Y™u",tbProp={0,5814,},nQuality=1,},
		{szName="Nguy÷t Khuy’t XUch Long ThÛc Y™u",tbProp={0,5824,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hµo Ki÷t ThÛc Y™u",tbProp={0,5834,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tham Lang Y™u ß∏i",tbProp={0,5844,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Li÷t D≠¨ng Y™u ß∏i",tbProp={0,5854,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Linh ßÈng Ph∏t ß∏i",tbProp={0,5864,},nQuality=1,},
		{szName="Nguy÷t Khuy’t ∂o ∂nh Ph∏t ß∏i",tbProp={0,5874,},nQuality=1,},
		{szName="Nguy÷t Khuy’t L®ng Phong Y™u ß∏i",tbProp={0,5884,},nQuality=1,},
		{szName="Nguy÷t Khuy’t MÈc VÚ Y™u ß∏i",tbProp={0,5894,},nQuality=1,},
		{szName="Nguy÷t Khuy’t DÀt ∂nh Y™u ß∏i",tbProp={0,5904,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Thanh Phong Y™u ß∏i",tbProp={0,5914,},nQuality=1,},

	},
	[6] = 
	{
		{szName="Nguy÷t Khuy’t Tr‰ng KiOp Cµ Sa",tbProp={0,5675,},nQuality=1,},
		{szName="Nguy÷t Khuy’t S∏t KiOp Cµ Sa",tbProp={0,5685,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph∏ KiOp Cµ Sa",tbProp={0,5695,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph n VÚ Kh∂i",tbProp={0,5705,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Y™n  Kh∂i",tbProp={0,5715,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tr≠Íng Kh´ng Kh∂i",tbProp={0,5725,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Kinh HÂng Ngh™ Th≠Íng VÚ Y",tbProp={0,5735,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hi”u Nguy÷t TuyOt Ti™u Y",tbProp={0,5745,},nQuality=1,},
		{szName="Nguy÷t Khuy’t T≠¨ng T≠ ˚ La Sam",tbProp={0,5755,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Nguy÷t Th∏i ßi÷p Y",tbProp={0,5765,},nQuality=1,},
		{szName="Nguy÷t Khuy’t B∏ch ßÈc CÊ Y",tbProp={0,5775,},nQuality=1,},
		{szName="Nguy÷t Khuy’t U Minh HÈ Gi∏p",tbProp={0,5785,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Th´i M÷nh Gi∏p",tbProp={0,5795,},nQuality=1,},
		{szName="Nguy÷t Khuy’t BU ßÈc Gi∏p Y",tbProp={0,5805,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Mπn ßÂ Gi∏p Y",tbProp={0,5815,},nQuality=1,},
		{szName="Nguy÷t Khuy’t XUch Long C∏i Y",tbProp={0,5825,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hµo Ki÷t C∏i Y",tbProp={0,5835,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tham Lang Gi∏p",tbProp={0,5845,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Li÷t D≠¨ng Gi∏p Y",tbProp={0,5855,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Linh ßÈng ßπo Bµo",tbProp={0,5865,},nQuality=1,},
		{szName="Nguy÷t Khuy’t ∂o ∂nh ßπo Bµo",tbProp={0,5875,},nQuality=1,},
		{szName="Nguy÷t Khuy’t L®ng Phong ßπo Bµo",tbProp={0,5885,},nQuality=1,},
		{szName="Nguy÷t Khuy’t MÈc VÚ ßπo Bµo",tbProp={0,5895,},nQuality=1,},
		{szName="Nguy÷t Khuy’t DÀt ∂nh Y",tbProp={0,5905,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Thanh Phong Y",tbProp={0,5915,},nQuality=1,},

	},
	[7] = 
	{
		{szName="Nguy÷t Khuy’t Tr‰ng KiOp Tri“n ThÒ",tbProp={0,5676,},nQuality=1,},
		{szName="Nguy÷t Khuy’t S∏t KiOp Ph∏p C´n",tbProp={0,5686,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph∏ KiOp GiÌi ßao",tbProp={0,5696,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph n VÚ Th«n ChÔy",tbProp={0,5706,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Y™n  Th≠¨ng",tbProp={0,5716,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tr≠Íng Kh´ng B∂o ßao",tbProp={0,5726,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Kinh HÂng B∂o Ki’m",tbProp={0,5736,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hi”u Nguy÷t Tri“n ThÒ",tbProp={0,5746,},nQuality=1,},
		{szName="Nguy÷t Khuy’t T≠¨ng T≠ B∂o ßao",tbProp={0,5756,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Nguy÷t Uy™n ¶¨ng ßao",tbProp={0,5766,},nQuality=1,},
		{szName="Nguy÷t Khuy’t B∏ch ßÈc Tri“n ThÒ",tbProp={0,5776,},nQuality=1,},
		{szName="Nguy÷t Khuy’t U Minh HuyOt Nh…n",tbProp={0,5786,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Th´i M÷nh Phi ßao",tbProp={0,5796,},nQuality=1,},
		{szName="Nguy÷t Khuy’t BU ßÈc TÙ Ti‘n",tbProp={0,5806,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Mπn ßÂ Phi Ti™u",tbProp={0,5816,},nQuality=1,},
		{szName="Nguy÷t Khuy’t XUch Long Tri“n ThÒ",tbProp={0,5826,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hµo Ki÷t Tr≠Óng",tbProp={0,5836,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tham Lang Th≠¨ng",tbProp={0,5846,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Li÷t D≠¨ng B∂o ßao",tbProp={0,5856,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Linh ßÈng Th«n Ki’m",tbProp={0,5866,},nQuality=1,},
		{szName="Nguy÷t Khuy’t ∂o ∂nh Th«n Ki’m",tbProp={0,5876,},nQuality=1,},
		{szName="Nguy÷t Khuy’t L®ng Phong B∂o ßao",tbProp={0,5886,},nQuality=1,},
		{szName="Nguy÷t Khuy’t MÈc VÚ Th«n Ki’m",tbProp={0,5896,},nQuality=1,},
		{szName="Nguy÷t Khuy’t DÀt ∂nh Ki’m",tbProp={0,5906,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Thanh Phong Ki’m",tbProp={0,5916,},nQuality=1,},
	},
	[8] = 
	{
		{szName="Nguy÷t Khuy’t Tr‰ng KiOp T®ng Hµi",tbProp={0,5677,},nQuality=1,},
		{szName="Nguy÷t Khuy’t S∏t KiOp T®ng Hµi",tbProp={0,5687,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph∏ KiOp T®ng Hµi",tbProp={0,5697,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph n VÚ Ngoa",tbProp={0,5707,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Y™n Ngoa",tbProp={0,5717,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tr≠Íng Kh´ng Ngoa",tbProp={0,5727,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Kinh HÂng LU",tbProp={0,5737,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hi”u Nguy÷t Ngoa",tbProp={0,5747,},nQuality=1,},
		{szName="Nguy÷t Khuy’t T≠¨ng T≠ Ngoa",tbProp={0,5757,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Nguy÷t Ngoa",tbProp={0,5767,},nQuality=1,},
		{szName="Nguy÷t Khuy’t B∏ch ßÈc Ngoa",tbProp={0,5777,},nQuality=1,},
		{szName="Nguy÷t Khuy’t U Minh Ngoa",tbProp={0,5787,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Th´i M÷nh LU",tbProp={0,5797,},nQuality=1,},
		{szName="Nguy÷t Khuy’t BU ßÈc LU",tbProp={0,5807,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Mπn ßÂ LU",tbProp={0,5817,},nQuality=1,},
		{szName="Nguy÷t Khuy’t XUch Long Ngoa",tbProp={0,5827,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hµo Ki÷t Ngoa",tbProp={0,5837,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tham Lang Ngoa",tbProp={0,5847,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Li÷t D≠¨ng Ngoa",tbProp={0,5857,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Linh ßÈng LU",tbProp={0,5867,},nQuality=1,},
		{szName="Nguy÷t Khuy’t ∂o ∂nh LU",tbProp={0,5877,},nQuality=1,},
		{szName="Nguy÷t Khuy’t L®ng Phong Ngoa",tbProp={0,5887,},nQuality=1,},
		{szName="Nguy÷t Khuy’t MÈc VÚ Ngoa",tbProp={0,5897,},nQuality=1,},
		{szName="Nguy÷t Khuy’t DÀt ∂nh Ngoa",tbProp={0,5907,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Thanh Phong Ngoa",tbProp={0,5917,},nQuality=1,},
	},
	[9] = 
	{
		{szName="Nguy÷t Khuy’t Tr‰ng KiOp Y™u TrÙy",tbProp={0,5678,},nQuality=1,},
		{szName="Nguy÷t Khuy’t S∏t KiOp Y™u TrÙy",tbProp={0,5688,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph∏ KiOp Y™u TrÙy",tbProp={0,5698,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph n VÚ Qu∂i TrÙy",tbProp={0,5708,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Y™n Y™u TrÙy",tbProp={0,5718,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tr≠Íng Kh´ng Y™u TrÙy",tbProp={0,5728,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Kinh HÂng H≠¨ng Nang",tbProp={0,5738,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hi”u Nguy÷t H≠¨ng Nang",tbProp={0,5748,},nQuality=1,},
		{szName="Nguy÷t Khuy’t T≠¨ng T≠ H≠¨ng Nang",tbProp={0,5758,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Nguy÷t H≠¨ng Nang",tbProp={0,5768,},nQuality=1,},
		{szName="Nguy÷t Khuy’t B∏ch ßÈc Y™u TrÙy",tbProp={0,5778,},nQuality=1,},
		{szName="Nguy÷t Khuy’t U Minh Y™u TrÙy",tbProp={0,5788,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Th´i M÷nh BÈi",tbProp={0,5798,},nQuality=1,},
		{szName="Nguy÷t Khuy’t BU ßÈc Y™u TrÙy",tbProp={0,5808,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Mπn ßÂ Y™u TrÙy",tbProp={0,5818,},nQuality=1,},
		{szName="Nguy÷t Khuy’t XUch Long Y™u TrÙy",tbProp={0,5828,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hµo Ki÷t Y™u TrÙy",tbProp={0,5838,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tham Lang BÈi",tbProp={0,5848,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Li÷t D≠¨ng BÈi",tbProp={0,5858,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Linh ßÈng Ng‰c BÈi",tbProp={0,5868,},nQuality=1,},
		{szName="Nguy÷t Khuy’t ∂o ∂nh Ng‰c BÈi",tbProp={0,5878,},nQuality=1,},
		{szName="Nguy÷t Khuy’t L®ng Phong BÈi",tbProp={0,5888,},nQuality=1,},
		{szName="Nguy÷t Khuy’t MÈc VÚ BÈi",tbProp={0,5898,},nQuality=1,},
		{szName="Nguy÷t Khuy’t DÀt ∂nh H≠¨ng Nang",tbProp={0,5908,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Thanh Phong H≠¨ng Nang",tbProp={0,5918,},nQuality=1,},
	},
	[10] = 
	{
		{szName="Nguy÷t Khuy’t Tr‰ng KiOp Huy“n Trang Chÿ Hoµn",tbProp={0,5679,},nQuality=1,},
		{szName="Nguy÷t Khuy’t S∏t KiOp ßπi Bi Chÿ Hoµn",tbProp={0,5689,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph∏ KiOp Ti”u Thoa Chÿ Hoµn",tbProp={0,5699,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Ph n VÚ TUch Tµ Chÿ Hoµn",tbProp={0,5709,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Y™n Tr«m H≠¨ng Chÿ Hoµn",tbProp={0,5719,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tr≠Íng Kh´ng PhÙng T◊nh Chÿ Hoµn",tbProp={0,5729,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Kinh HÂng BUch Ng‰c Chÿ Hoµn",tbProp={0,5739,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hi”u Nguy÷t ThÒy Tinh Chÿ Hoµn",tbProp={0,5749,},nQuality=1,},
		{szName="Nguy÷t Khuy’t T≠¨ng T≠ Hæc Ng‰c Chÿ Hoµn",tbProp={0,5759,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Phong Nguy÷t San HÂ Chÿ Hoµn",tbProp={0,5769,},nQuality=1,},
		{szName="Nguy÷t Khuy’t B∏ch ßÈc Kh´ L©u Chÿ Hoµn",tbProp={0,5779,},nQuality=1,},
		{szName="Nguy÷t Khuy’t U Minh U Minh GiÌi",tbProp={0,5789,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Th´i M÷nh TUch Di÷p Chÿ Hoµn",tbProp={0,5799,},nQuality=1,},
		{szName="Nguy÷t Khuy’t BU ßÈc Kim Thi“m Chÿ Hoµn",tbProp={0,5809,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Mπn ßÂ ßoπt HÂn Chÿ Hoµn",tbProp={0,5819,},nQuality=1,},
		{szName="Nguy÷t Khuy’t XUch Long Thi™n Lu Chÿ Hoµn",tbProp={0,5829,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Hµo Ki÷t Linh Thπch Ph∂n Chÿ",tbProp={0,5839,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Tham Lang HuyOt ThÛ Ph∂n Chÿ",tbProp={0,5849,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Li÷t D≠¨ng D≠¨ng Vi™m Chÿ Hoµn",tbProp={0,5859,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Linh ßÈng ßπo Hµnh Chÿ Hoµn",tbProp={0,5869,},nQuality=1,},
		{szName="Nguy÷t Khuy’t ∂o ∂nh B t Di÷t Ph∏p GiÌi",tbProp={0,5979,},nQuality=1,},
		{szName="Nguy÷t Khuy’t L®ng Phong Cµn Kh´n GiÌi",tbProp={0,5889,},nQuality=1,},
		{szName="Nguy÷t Khuy’t MÈc VÚ D≠¨ng Chi Chÿ Hoµn",tbProp={0,5899,},nQuality=1,},
		{szName="Nguy÷t Khuy’t DÀt ∂nh Thi™n C¨ Chÿ Hoµn",tbProp={0,5909,},nQuality=1,},
		{szName="Nguy÷t Khuy’t Thanh Phong ß~a TUch Chÿ Hoµn",tbProp={0,5919,},nQuality=1,},
	}
}


tbEquip_JinWuEx = 
{
	[1] = 
	{
		{szName="Tinh S≠¨ng KhÊ ßO Ch©u Li™n",tbProp={0,5379,},nQuality=1,},
		{szName="Tinh S≠¨ng Di÷t ßO PhÀt Ch©u",tbProp={0,5389,},nQuality=1,},
		{szName="Tinh S≠¨ng ßπo ßO Hπng Li™n",tbProp={0,5399,},nQuality=1,},
		{szName="Tinh S≠¨ng Th´n Tµ Hπng Li™n",tbProp={0,5409,},nQuality=1,},
		{szName="Tinh S≠¨ng L≠u Kim Hπng Li™n",tbProp={0,5419,},nQuality=1,},
		{szName="Tinh S≠¨ng L˜ S≠¨ng Hπng Li™n",tbProp={0,5429,},nQuality=1,},
		{szName="Tinh S≠¨ng Lπc Anh Ch©u Li™n",tbProp={0,5439,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph t Huy÷t Ch©u Li™n",tbProp={0,5449,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi™n H≠¨ng Ch©u Li™n",tbProp={0,5459,},nQuality=1,},
		{szName="Tinh S≠¨ng Th∏i VÀn Ch©u Li™n",tbProp={0,5469,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi“m Phi Hπng Li™n",tbProp={0,5479,},nQuality=1,},
		{szName="Tinh S≠¨ng PhÙ CËt Hπng Li™n",tbProp={0,5489,},nQuality=1,},
		{szName="Tinh S≠¨ng L∑nh HuyOt Hπng Li™n",tbProp={0,5499,},nQuality=1,},
		{szName="Tinh S≠¨ng NÈ Li™n Hπng Li™n",tbProp={0,5509,},nQuality=1,},
		{szName="Tinh S≠¨ng Truy M÷nh Hπng Li™n",tbProp={0,5519,},nQuality=1,},
		{szName="Tinh S≠¨ng M∑nh Long Hπng Li™n",tbProp={0,5529,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph∏ LÁ Hπng Li™n",tbProp={0,5539,},nQuality=1,},
		{szName="Tinh S≠¨ng Luy÷n NhÀt Hπng Quy”n",tbProp={0,5549,},nQuality=1,},
		{szName="Tinh S≠¨ng KhËc Vi™m Hπng Li™n",tbProp={0,5559,},nQuality=1,},
		{szName="Tinh S≠¨ng Ch n S¨n PhÔ",tbProp={0,5569,},nQuality=1,},
		{szName="Tinh S≠¨ng Qu©n Uy PhÔ",tbProp={0,5579,},nQuality=1,},
		{szName="Tinh S≠¨ng Minh L´i Hπng Li™n",tbProp={0,5589,},nQuality=1,},
		{szName="Tinh S≠¨ng Oanh Minh PhÔ",tbProp={0,5599,},nQuality=1,},
		{szName="Tinh S≠¨ng Hπo Thi™n Hπng Li™n",tbProp={0,5609,},nQuality=1,},
		{szName="Tinh S≠¨ng Thanh H≠ Hπng Li™n",tbProp={0,5619,},nQuality=1,},
	},
	[2] = 
	{
		{szName="Tinh S≠¨ng KhÊ ßO T®ng Mπo",tbProp={0,5380,},nQuality=1,},
		{szName="Tinh S≠¨ng Di÷t ßO T®ng Mπo",tbProp={0,5390,},nQuality=1,},
		{szName="Tinh S≠¨ng ßπo ßO T®ng Mπo",tbProp={0,5400,},nQuality=1,},
		{szName="Tinh S≠¨ng Th´n Tµ Kh´i",tbProp={0,5410,},nQuality=1,},
		{szName="Tinh S≠¨ng L≠u Kim Kh´i",tbProp={0,5420,},nQuality=1,},
		{szName="Tinh S≠¨ng L˜ S≠¨ng Kh´i",tbProp={0,5430,},nQuality=1,},
		{szName="Tinh S≠¨ng Lπc Anh Ph∏t ß∏i",tbProp={0,5440,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph t Huy÷t Ph∏t ß∏i",tbProp={0,5450,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi™n H≠¨ng Tr©m",tbProp={0,5460,},nQuality=1,},
		{szName="Tinh S≠¨ng Th∏i VÀn Tr©m",tbProp={0,5470,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi“m Phi Ph∏t ß∏i",tbProp={0,5480,},nQuality=1,},
		{szName="Tinh S≠¨ng PhÙ CËt Ph∏t ß∏i",tbProp={0,5490,},nQuality=1,},
		{szName="Tinh S≠¨ng L∑nh HuyOt Qu∏n",tbProp={0,5500,},nQuality=1,},
		{szName="Tinh S≠¨ng NÈ Li™n Qu∏n",tbProp={0,5510,},nQuality=1,},
		{szName="Tinh S≠¨ng Truy M÷nh Ph∏t Qu∏n",tbProp={0,5520,},nQuality=1,},
		{szName="Tinh S≠¨ng M∑nh Long ß«u Hoµn",tbProp={0,5530,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph∏ LÁ ß«u Hoµn",tbProp={0,5540,},nQuality=1,},
		{szName="Tinh S≠¨ng Luy÷n NhÀt Kh´i",tbProp={0,5550,},nQuality=1,},
		{szName="Tinh S≠¨ng KhËc Vi™m Qu∏n Mi÷n",tbProp={0,5560,},nQuality=1,},
		{szName="Tinh S≠¨ng Ch n S¨n Qu∏n",tbProp={0,5570,},nQuality=1,},
		{szName="Tinh S≠¨ng Qu©n Uy Qu∏n",tbProp={0,5580,},nQuality=1,},
		{szName="Tinh S≠¨ng Minh L´i ßπo Qu∏n",tbProp={0,5590,},nQuality=1,},
		{szName="Tinh S≠¨ng Oanh Minh ßπo Qu∏n",tbProp={0,5600,},nQuality=1,},
		{szName="Tinh S≠¨ng Hπo Thi™n Qu∏n",tbProp={0,5610,},nQuality=1,},
		{szName="Tinh S≠¨ng Thanh H≠ Qu∏n",tbProp={0,5620,},nQuality=1,},
	},
	[3] = 
	{
		{szName="Tinh S≠¨ng KhÊ ßO Kim Thi“n Chÿ Hoµn",tbProp={0,5381,},nQuality=1,},
		{szName="Tinh S≠¨ng Di÷t ßO ßπi To Chÿ Hoµn",tbProp={0,5391,},nQuality=1,},
		{szName="Tinh S≠¨ng ßπo ßO ßπi Thoa Chÿ Hoµn",tbProp={0,5401,},nQuality=1,},
		{szName="Tinh S≠¨ng Th´n Tµ Nh≠ u Chÿ Hoµn",tbProp={0,5411,},nQuality=1,},
		{szName="Tinh S≠¨ng L≠u Kim ßµn H≠¨ng Chÿ Hoµn",tbProp={0,5421,},nQuality=1,},
		{szName="Tinh S≠¨ng L˜ S≠¨ng Long ß∂m Chÿ Hoµn",tbProp={0,5431,},nQuality=1,},
		{szName="Tinh S≠¨ng Lπc Anh Minh Ch©u Chÿ Hoµn",tbProp={0,5441,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph t Huy÷t L≠u Li Chÿ Hoµn",tbProp={0,5451,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi™n H≠¨ng TuyOt Ng‰c Chÿ Hoµn",tbProp={0,5461,},nQuality=1,},
		{szName="Tinh S≠¨ng Th∏i VÀn Linh Lung Chÿ Hoµn",tbProp={0,5471,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi“m Phi HuyOt TUch Chÿ Hoµn	",tbProp={0,5481,},nQuality=1,},
		{szName="Tinh S≠¨ng PhÙ CËt Huy“n ¢m GiÌi",tbProp={0,5491,},nQuality=1,},
		{szName="Tinh S≠¨ng L∑nh HuyOt Phi Hoa Chÿ Hoµn",tbProp={0,5501,},nQuality=1,},
		{szName="Tinh S≠¨ng NÈ Li™n Linh Xµ Chÿ Hoµn",tbProp={0,5511,},nQuality=1,},
		{szName="Tinh S≠¨ng Truy M÷nh NhiOp Ph∏ch Chÿ Hoµn",tbProp={0,5521,},nQuality=1,},
		{szName="Tinh S≠¨ng M∑nh Long Vπn Tr≠Óng Chÿ Hoµn",tbProp={0,5531,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph∏ LÁ LÙc Long Ban Chÿ",tbProp={0,5541,},nQuality=1,},
		{szName="Tinh S≠¨ng Luy÷n NhÀt Li÷t Di‘m Ban Chÿ	",tbProp={0,5551,},nQuality=1,},
		{szName="Tinh S≠¨ng KhËc Vi™m Dong Nham Chÿ Hoµn",tbProp={0,5561,},nQuality=1,},
		{szName="Tinh S≠¨ng Ch n S¨n V‹nh Sinh Chÿ Hoµn",tbProp={0,5571,},nQuality=1,},
		{szName="Tinh S≠¨ng Qu©n Uy Hªng Cˆu Ph∏p GiÌi",tbProp={0,5581,},nQuality=1,},
		{szName="Tinh S≠¨ng Minh L´i Tr‰ng D≠¨ng GiÌi",tbProp={0,5591,},nQuality=1,},
		{szName="Tinh S≠¨ng Oanh Minh Linh Ng‰c Chÿ Hoµn	",tbProp={0,5601,},nQuality=1,},
		{szName="Tinh S≠¨ng Hπo Thi™n Thi™n Th«n Chÿ Hoµn",tbProp={0,5611,},nQuality=1,},
		{szName="Tinh S≠¨ng Thanh H≠ ß~a Vi Chÿ Hoµn",tbProp={0,5621,},nQuality=1,},
	},
	[4] =
	{
		{szName="Tinh S≠¨ng KhÊ ßO HÈ Uy”n",tbProp={0,5382,},nQuality=1,},
		{szName="Tinh S≠¨ng Di÷t ßO HÈ Uy”n",tbProp={0,5392,},nQuality=1,},
		{szName="Tinh S≠¨ng ßπo ßO HÈ Uy”n",tbProp={0,5402,},nQuality=1,},
		{szName="Tinh S≠¨ng Th´n Tµ ThÛc Uy”n",tbProp={0,5412,},nQuality=1,},
		{szName="Tinh S≠¨ng L≠u Kim ThÛc Uy”n",tbProp={0,5422,},nQuality=1,},
		{szName="Tinh S≠¨ng L˜ S≠¨ng ThÛc Uy”n",tbProp={0,5432,},nQuality=1,},
		{szName="Tinh S≠¨ng Lπc Anh L≠u V©n TÙ",tbProp={0,5442,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph t Huy÷t TuyOt ∂nh TÙ",tbProp={0,5452,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi™n H≠¨ng C»m TÛ HÈ Uy”n",tbProp={0,5462,},nQuality=1,},
		{szName="Tinh S≠¨ng Th∏i VÀn Sinh Hoa ThÒ Trπc",tbProp={0,5472,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi“m Phi HÈ Uy”n",tbProp={0,5482,},nQuality=1,},
		{szName="Tinh S≠¨ng PhÙ CËt HÈ Uy”n",tbProp={0,5492,},nQuality=1,},
		{szName="Tinh S≠¨ng L∑nh HuyOt HÈ Uy”n",tbProp={0,5502,},nQuality=1,},
		{szName="Tinh S≠¨ng NÈ Li™n HÈ Uy”n",tbProp={0,5512,},nQuality=1,},
		{szName="Tinh S≠¨ng Truy M÷nh HÈ Uy”n",tbProp={0,5522,},nQuality=1,},
		{szName="Tinh S≠¨ng M∑nh Long HÈ Uy”n",tbProp={0,5532,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph∏ LÁ HÈ Uy”n",tbProp={0,5542,},nQuality=1,},
		{szName="Tinh S≠¨ng Luy÷n NhÀt HÈ Uy”n",tbProp={0,5552,},nQuality=1,},
		{szName="Tinh S≠¨ng KhËc Vi™m HÈ Uy”n",tbProp={0,5562,},nQuality=1,},
		{szName="Tinh S≠¨ng Ch n S¨n TÙ",tbProp={0,5572,},nQuality=1,},
		{szName="Tinh S≠¨ng Qu©n Uy TÙ",tbProp={0,5582,},nQuality=1,},
		{szName="Tinh S≠¨ng Minh L´i HÈ Uy”n",tbProp={0,5592,},nQuality=1,},
		{szName="Tinh S≠¨ng Oanh Minh HÈ Uy”n",tbProp={0,5602,},nQuality=1,},
		{szName="Tinh S≠¨ng Hπo Thi™n HÈ Uy”n",tbProp={0,5612,},nQuality=1,},
		{szName="Tinh S≠¨ng Thanh H≠ HÈ Uy”n",tbProp={0,5622,},nQuality=1,},
	},
	[5] =
	{
		{szName="Tinh S≠¨ng KhÊ ßO Y™u ß∏i",tbProp={0,5383,},nQuality=1,},
		{szName="Tinh S≠¨ng Di÷t ßO Y™u ß∏i",tbProp={0,5393,},nQuality=1,},
		{szName="Tinh S≠¨ng ßπo ßO Y™u ß∏i",tbProp={0,5403,},nQuality=1,},
		{szName="Tinh S≠¨ng Th´n Tµ Y™u ß∏i",tbProp={0,5413,},nQuality=1,},
		{szName="Tinh S≠¨ng L≠u Kim Y™u ß∏i",tbProp={0,5423,},nQuality=1,},
		{szName="Tinh S≠¨ng L˜ S≠¨ng Y™u ß∏i",tbProp={0,5433,},nQuality=1,},
		{szName="Tinh S≠¨ng Lπc Anh Ti ß∏i",tbProp={0,5443,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph t Huy÷t Ti ß∏i",tbProp={0,5453,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi™n H≠¨ng Y™u ß∏i",tbProp={0,5463,},nQuality=1,},
		{szName="Tinh S≠¨ng Th∏i VÀn Ti ß∏i",tbProp={0,5473,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi“m Phi Y™u ß∏i",tbProp={0,5483,},nQuality=1,},
		{szName="Tinh S≠¨ng PhÙ CËt Y™u ß∏i",tbProp={0,5493,},nQuality=1,},
		{szName="Tinh S≠¨ng L∑nh HuyOt Tri“n Y™u",tbProp={0,5503,},nQuality=1,},
		{szName="Tinh S≠¨ng NÈ Li™n ThÛc Y™u",tbProp={0,5513,},nQuality=1,},
		{szName="Tinh S≠¨ng Truy M÷nh ThÛc Y™u",tbProp={0,5523,},nQuality=1,},
		{szName="Tinh S≠¨ng M∑nh Long ThÛc Y™u",tbProp={0,5533,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph∏ LÁ ThÛc Y™u",tbProp={0,5543,},nQuality=1,},
		{szName="Tinh S≠¨ng Luy÷n NhÀt Y™u ß∏i",tbProp={0,5553,},nQuality=1,},
		{szName="Tinh S≠¨ng KhËc Vi™m Y™u ß∏i",tbProp={0,5563,},nQuality=1,},
		{szName="Tinh S≠¨ng Ch n S¨n Ph∏p ß∏i",tbProp={0,5573,},nQuality=1,},
		{szName="Tinh S≠¨ng Qu©n Uy Ph∏p ß∏i",tbProp={0,5583,},nQuality=1,},
		{szName="Tinh S≠¨ng Minh L´i Y™u ß∏i",tbProp={0,5593,},nQuality=1,},
		{szName="Tinh S≠¨ng Oanh Minh Y™u ß∏i",tbProp={0,5603,},nQuality=1,},
		{szName="Tinh S≠¨ng Hπo Thi™n Y™u ß∏i",tbProp={0,5613,},nQuality=1,},
		{szName="Tinh S≠¨ng Thanh H≠ Y™u ß∏i",tbProp={0,5623,},nQuality=1,},
	},
	[6] = 
	{
		{szName="Tinh S≠¨ng KhÊ ßO Cµ Sa",tbProp={0,5384,},nQuality=1,},
		{szName="Tinh S≠¨ng Di÷t ßO Cµ Sa",tbProp={0,5394,},nQuality=1,},
		{szName="Tinh S≠¨ng ßπo ßO Cµ Sa",tbProp={0,5404,},nQuality=1,},
		{szName="Tinh S≠¨ng Th´n Tµ Kh∂i",tbProp={0,5414,},nQuality=1,},
		{szName="Tinh S≠¨ng L≠u Kim Kh∂i",tbProp={0,5424,},nQuality=1,},
		{szName="Tinh S≠¨ng L˜ S≠¨ng Kh∂i",tbProp={0,5434,},nQuality=1,},
		{szName="Tinh S≠¨ng Lπc Anh Ngh™ Th≠Íng VÚ Y",tbProp={0,5444,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph t Huy÷t TuyOt Ti™u Y",tbProp={0,5454,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi™n H≠¨ng KhÎi La Sam",tbProp={0,5464,},nQuality=1,},
		{szName="Tinh S≠¨ng Th∏i VÀn Th∏i ßi÷p Y",tbProp={0,5474,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi“m Phi CÊ Y",tbProp={0,5484,},nQuality=1,},
		{szName="Tinh S≠¨ng PhÙ CËt HÈ Gi∏p",tbProp={0,5494,},nQuality=1,},
		{szName="Tinh S≠¨ng L∑nh HuyOt Gi∏p",tbProp={0,5504,},nQuality=1,},
		{szName="Tinh S≠¨ng NÈ Li™n Gi∏p Y",tbProp={0,5514,},nQuality=1,},
		{szName="Tinh S≠¨ng Truy M÷nh Gi∏p Y",tbProp={0,5524,},nQuality=1,},
		{szName="Tinh S≠¨ng M∑nh Long C∏i Y",tbProp={0,5534,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph∏ LÁ C∏i Y",tbProp={0,5544,},nQuality=1,},
		{szName="Tinh S≠¨ng Luy÷n NhÀt Gi∏p",tbProp={0,5554,},nQuality=1,},
		{szName="Tinh S≠¨ng KhËc Vi™m Gi∏p Y",tbProp={0,5564,},nQuality=1,},
		{szName="Tinh S≠¨ng Ch n S¨n ßπo Bµo",tbProp={0,5574,},nQuality=1,},
		{szName="Tinh S≠¨ng Qu©n Uy ßπo Bµo",tbProp={0,5584,},nQuality=1,},
		{szName="Tinh S≠¨ng Minh L´i ßπo Bµo",tbProp={0,5594,},nQuality=1,},
		{szName="Tinh S≠¨ng Oanh Minh ßπo Bµo",tbProp={0,5604,},nQuality=1,},
		{szName="Tinh S≠¨ng Hπo Thi™n Y",tbProp={0,5614,},nQuality=1,},
		{szName="Tinh S≠¨ng Thanh H≠ Y",tbProp={0,5624,},nQuality=1,},
	},
	[7] = 
	{
		{szName="Tinh S≠¨ng KhÊ ßO Tri“n ThÒ",tbProp={0,5385,},nQuality=1,},
		{szName="Tinh S≠¨ng Di÷t ßO Ph∏p C´n",tbProp={0,5395,},nQuality=1,},
		{szName="Tinh S≠¨ng ßπo ßO GiÌi ßao",tbProp={0,5405,},nQuality=1,},
		{szName="Tinh S≠¨ng Th´n Tµ Th«n ChÔy",tbProp={0,5415,},nQuality=1,},
		{szName="Tinh S≠¨ng L≠u Kim Th≠¨ng",tbProp={0,5425,},nQuality=1,},
		{szName="Tinh S≠¨ng L˜ S≠¨ng B∂o ßao",tbProp={0,5435,},nQuality=1,},
		{szName="Tinh S≠¨ng Lπc Anh B∂o Ki’m",tbProp={0,5445,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph t Huy÷t Tri“n ThÒ",tbProp={0,5455,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi™n H≠¨ng B∂o ßao",tbProp={0,5465,},nQuality=1,},
		{szName="Tinh S≠¨ng Th∏i VÀn Uy™n ¶¨ng ßao",tbProp={0,5475,},nQuality=1,},		
		{szName="Tinh S≠¨ng Thi“m Phi Tri“n ThÒ",tbProp={0,5485,},nQuality=1,},		
		{szName="Tinh S≠¨ng PhÙ CËt HuyOt NhÀn",tbProp={0,5495,},nQuality=1,},
		{szName="Tinh S≠¨ng L∑nh HuyOt Phi ßao",tbProp={0,5505,},nQuality=1,},
		{szName="Tinh S≠¨ng NÈ Li™n TÙ Ti‘n",tbProp={0,5515,},nQuality=1,},
		{szName="Tinh S≠¨ng Truy M÷nh Phi Ti™u",tbProp={0,5525,},nQuality=1,},
		{szName="Tinh S≠¨ng M∑nh Long Tri“n ThÒ",tbProp={0,5535,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph∏ LÁ Tr≠Óng",tbProp={0,5545,},nQuality=1,},
		{szName="Tinh S≠¨ng Luy÷n NhÀt Th≠¨ng",tbProp={0,5555,},nQuality=1,},
		{szName="Tinh S≠¨ng KhËc Vi™m B∂o ßao",tbProp={0,5565,},nQuality=1,},
		{szName="Tinh S≠¨ng Ch n S¨n Th«n Ki’m",tbProp={0,5575,},nQuality=1,},
		{szName="Tinh S≠¨ng Qu©n Uy Th«n Ki’m",tbProp={0,5585,},nQuality=1,},
		{szName="Tinh S≠¨ng Minh L´i B∂o ßao",tbProp={0,5595,},nQuality=1,},
		{szName="Tinh S≠¨ng Oanh Minh Th«n Ki’m",tbProp={0,5605,},nQuality=1,},
		{szName="Tinh S≠¨ng Hπo Thi™n Ki’m",tbProp={0,5615,},nQuality=1,},
		{szName="Tinh S≠¨ng Thanh H≠ Ki’m",tbProp={0,5625,},nQuality=1,},
	},
	[8] = 
	{
		{szName="Tinh S≠¨ng KhÊ ßO T®ng Hµi",tbProp={0,5386,},nQuality=1,},
		{szName="Tinh S≠¨ng Di÷t ßO T®ng Hµi",tbProp={0,5396,},nQuality=1,},
		{szName="Tinh S≠¨ng ßπo ßO T®ng Hµi",tbProp={0,5406,},nQuality=1,},
		{szName="Tinh S≠¨ng Th´n Tµ Ngoa",tbProp={0,5416,},nQuality=1,},
		{szName="Tinh S≠¨ng L≠u Kim Ngoa",tbProp={0,5426,},nQuality=1,},
		{szName="Tinh S≠¨ng L˜ S≠¨ng Ngoa",tbProp={0,5436,},nQuality=1,},
		{szName="Tinh S≠¨ng Lπc Anh L˜",tbProp={0,5446,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph t Huy÷t Ngoa",tbProp={0,5456,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi™n H≠¨ng Ngoa",tbProp={0,5466,},nQuality=1,},
		{szName="Tinh S≠¨ng Th∏i VÀn Ngoa",tbProp={0,5476,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi“m Phi Ngoa",tbProp={0,5486,},nQuality=1,},
		{szName="Tinh S≠¨ng PhÙ CËt Ngoa",tbProp={0,5496,},nQuality=1,},
		{szName="Tinh S≠¨ng L∑nh HuyOt L˜",tbProp={0,5506,},nQuality=1,},
		{szName="Tinh S≠¨ng NÈ Li™n L˜",tbProp={0,5516,},nQuality=1,},
		{szName="Tinh S≠¨ng Truy M÷nh L˜",tbProp={0,5526,},nQuality=1,},
		{szName="Tinh S≠¨ng M∑nh Long Ngoa",tbProp={0,5536,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph∏ LÁ Ngoa",tbProp={0,5546,},nQuality=1,},
		{szName="Tinh S≠¨ng Luy÷n NhÀt Ngoa",tbProp={0,5556,},nQuality=1,},
		{szName="Tinh S≠¨ng KhËc Vi™m Ngoa",tbProp={0,5566,},nQuality=1,},
		{szName="Tinh S≠¨ng Ch n S¨n L˜",tbProp={0,5576,},nQuality=1,},
		{szName="Tinh S≠¨ng Qu©n Uy L˜",tbProp={0,5586,},nQuality=1,},
		{szName="Tinh S≠¨ng Minh L´i Ngoa",tbProp={0,5596,},nQuality=1,},
		{szName="Tinh S≠¨ng Oanh Minh Ngoa",tbProp={0,5606,},nQuality=1,},
		{szName="Tinh S≠¨ng Hπo Thi™n Ngoa",tbProp={0,5616,},nQuality=1,},
		{szName="Tinh S≠¨ng Thanh H≠ Ngoa",tbProp={0,5626,},nQuality=1,},
	},
	[9] = 
	{
		{szName="Tinh S≠¨ng KhÊ ßO Y™u TrÙy",tbProp={0,5387,},nQuality=1,},
		{szName="Tinh S≠¨ng Di÷t ßO Y™u TrÙy",tbProp={0,5397,},nQuality=1,},
		{szName="Tinh S≠¨ng ßπo ßO Y™u TrÙy",tbProp={0,5407,},nQuality=1,},
		{szName="Tinh S≠¨ng Th´n Tµ Qu∂i TrÙy",tbProp={0,5417,},nQuality=1,},
		{szName="Tinh S≠¨ng L≠u Kim Y™u TrÙy",tbProp={0,5427,},nQuality=1,},
		{szName="Tinh S≠¨ng L˜ S≠¨ng Y™u TrÙy",tbProp={0,5437,},nQuality=1,},
		{szName="Tinh S≠¨ng Lπc Anh H≠¨ng Nang",tbProp={0,5447,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph t Huy÷t H≠¨ng Nang",tbProp={0,5457,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi™n H≠¨ng H≠¨ng Nang",tbProp={0,5467,},nQuality=1,},
		{szName="Tinh S≠¨ng Th∏i VÀn H≠¨ng Nang",tbProp={0,5477,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi“m Phi Y™u TrÙy",tbProp={0,5487,},nQuality=1,},
		{szName="Tinh S≠¨ng PhÙ CËt Y™u TrÙy",tbProp={0,5497,},nQuality=1,},
		{szName="Tinh S≠¨ng L∑nh HuyOt BÈi",tbProp={0,5507,},nQuality=1,},
		{szName="Tinh S≠¨ng NÈ Li™n Y™u TrÙy",tbProp={0,5517,},nQuality=1,},
		{szName="Tinh S≠¨ng Truy M÷nh Y™u TrÙy",tbProp={0,5527,},nQuality=1,},
		{szName="Tinh S≠¨ng M∑nh Long Y™u TrÙy",tbProp={0,5537,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph∏ LÁ Y™u TrÙy",tbProp={0,5547,},nQuality=1,},
		{szName="Tinh S≠¨ng Luy÷n NhÀt BÈi",tbProp={0,5557,},nQuality=1,},
		{szName="Tinh S≠¨ng KhËc Vi™m BÈi",tbProp={0,5567,},nQuality=1,},
		{szName="Tinh S≠¨ng Ch n S¨n Ng‰c BÈi",tbProp={0,5577,},nQuality=1,},
		{szName="Tinh S≠¨ng Qu©n Uy Ng‰c BÈi",tbProp={0,5587,},nQuality=1,},
		{szName="Tinh S≠¨ng Minh L´i BÈi",tbProp={0,5597,},nQuality=1,},
		{szName="Tinh S≠¨ng Oanh Minh BÈi",tbProp={0,5607,},nQuality=1,},
		{szName="Tinh S≠¨ng Hπo Thi™n H≠¨ng Nang",tbProp={0,5617,},nQuality=1,},
		{szName="Tinh S≠¨ng Thanh H≠ H≠¨ng Nang",tbProp={0,5627,},nQuality=1,},
	},
	[10] = 
	{
		{szName="Tinh S≠¨ng KhÊ ßO Huy“n Trang Chÿ Hoµn",tbProp={0,5388,},nQuality=1,},
		{szName="Tinh S≠¨ng Di÷t ßO ßπi Bi Chÿ Hoµn",tbProp={0,5398,},nQuality=1,},
		{szName="Tinh S≠¨ng ßπo ßO Ti”u Thoa Chÿ Hoµn",tbProp={0,5408,},nQuality=1,},
		{szName="Tinh S≠¨ng Th´n Tµ T~ch Tµ Chÿ Hoµn",tbProp={0,5418,},nQuality=1,},
		{szName="Tinh S≠¨ng L≠u Kim Tr«m H≠¨ng Chÿ Hoµn",tbProp={0,5428,},nQuality=1,},
		{szName="Tinh S≠¨ng L˜ S≠¨ng Ph≠Óng T◊nh Chÿ Hoµn",tbProp={0,5438,},nQuality=1,},
		{szName="Tinh S≠¨ng Lπc Anh BUch Ng‰c Chÿ Hoµn",tbProp={0,5448,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph t Huy÷t ThÒy Tinh Chÿ Hoµn",tbProp={0,5458,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi™n H≠¨ng M∆c Ng‰c Chÿ Hoµn",tbProp={0,5468,},nQuality=1,},
		{szName="Tinh S≠¨ng Th∏i VÀn San H´ Chÿ Hoµn",tbProp={0,5478,},nQuality=1,},
		{szName="Tinh S≠¨ng Thi“m Phi Kh´ L©u Chÿ Hoµn",tbProp={0,5488,},nQuality=1,},
		{szName="Tinh S≠¨ng PhÙ CËt Huy“n U GiÌi",tbProp={0,5498,},nQuality=1,},
		{szName="Tinh S≠¨ng L∑nh HuyOt TrUch Di÷p Chÿ Hoµn",tbProp={0,5508,},nQuality=1,},
		{szName="Tinh S≠¨ng NÈ Li™n Kim Thi“m Chÿ Hoµn",tbProp={0,5518,},nQuality=1,},
		{szName="Tinh S≠¨ng Truy M÷nh ßoπt HÂn Chÿ Hoµn",tbProp={0,5528,},nQuality=1,},
		{szName="Tinh S≠¨ng M∑nh Long Thi™n LU Chÿ Hoµn	",tbProp={0,5538,},nQuality=1,},
		{szName="Tinh S≠¨ng Ph∏ LÁ Linh Thπch Ban Chÿ",tbProp={0,5548},nQuality=1,},
		{szName="Tinh S≠¨ng Luy÷n NhÀt HuyOt ThÛ Ban Chÿ",tbProp={0,5558,},nQuality=1,},
		{szName="Tinh S≠¨ng KhËc Vi™m D≠¨ng Vi™m Chÿ Hoµn",tbProp={0,5568,},nQuality=1,},
		{szName="Tinh S≠¨ng Ch n S¨n ßπo Hµnh Chÿ Hoµn",tbProp={0,5578,},nQuality=1,},
		{szName="KTinh S≠¨ng Qu©n Uy B t Di÷t Ph∏p GiÌi",tbProp={0,5588,},nQuality=1,},
		{szName="Tinh S≠¨ng Minh L´i Cµn Kh´n GiÌi",tbProp={0,5598,},nQuality=1,},
		{szName="Tinh S≠¨ng Oanh Minh D≠¨ng Chi Chÿ Hoµn",tbProp={0,5608,},nQuality=1,},
		{szName="Tinh S≠¨ng Hπo Thi™n Thi™n C¨ Chÿ Hoµn",tbProp={0,5618,},nQuality=1,},
		{szName="Tinh S≠¨ng Thanh H≠ ß~a TUch Chÿ Hoµn",tbProp={0,5628,},nQuality=1,},
	},
}