tbEquip_TS = 
{
		[1] = 
	{
		{szName="Tinh S­¬ng Khæ §O Ch©u Liªn",tbProp={0,5379,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O PhËt Ch©u",tbProp={0,5389,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O H¹ng Liªn",tbProp={0,5399,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ H¹ng Liªn",tbProp={0,5409,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim H¹ng Liªn",tbProp={0,5419,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng H¹ng Liªn",tbProp={0,5429,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh Ch©u Liªn",tbProp={0,5439,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt Ch©u Liªn",tbProp={0,5449,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng Ch©u Liªn",tbProp={0,5459,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Ch©u Liªn",tbProp={0,5469,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi H¹ng Liªn",tbProp={0,5479,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt H¹ng Liªn",tbProp={0,5489,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt H¹ng Liªn",tbProp={0,5499,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn H¹ng Liªn",tbProp={0,5509,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh H¹ng Liªn",tbProp={0,5519,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long H¹ng Liªn",tbProp={0,5529,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç H¹ng Liªn",tbProp={0,5539,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt H¹ng QuyÓn",tbProp={0,5549,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm H¹ng Liªn",tbProp={0,5559,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n Phï",tbProp={0,5569,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy Phï",tbProp={0,5579,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i H¹ng Liªn",tbProp={0,5589,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh Phï",tbProp={0,5599,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn H¹ng Liªn",tbProp={0,5609,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ H¹ng Liªn",tbProp={0,5619,},nQuality=1,},
	},
	[2] = 
	{
		{szName="Tinh S­¬ng Khæ §O T¨ng M¹o",tbProp={0,5380,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O T¨ng M¹o",tbProp={0,5390,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O T¨ng M¹o",tbProp={0,5400,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Kh«i",tbProp={0,5410,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Kh«i",tbProp={0,5420,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Kh«i",tbProp={0,5430,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh Ph¸t §¸i",tbProp={0,5440,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt Ph¸t §¸i",tbProp={0,5450,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng Tr©m",tbProp={0,5460,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Tr©m",tbProp={0,5470,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Ph¸t §¸i",tbProp={0,5480,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt Ph¸t §¸i",tbProp={0,5490,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt Qu¸n",tbProp={0,5500,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Qu¸n",tbProp={0,5510,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh Ph¸t Qu¸n",tbProp={0,5520,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long §Çu Hoµn",tbProp={0,5530,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç §Çu Hoµn",tbProp={0,5540,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Kh«i",tbProp={0,5550,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Qu¸n MiÖn",tbProp={0,5560,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n Qu¸n",tbProp={0,5570,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy Qu¸n",tbProp={0,5580,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i §¹o Qu¸n",tbProp={0,5590,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh §¹o Qu¸n",tbProp={0,5600,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Qu¸n",tbProp={0,5610,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ Qu¸n",tbProp={0,5620,},nQuality=1,},
	},
	[3] = 
	{
		{szName="Tinh S­¬ng Khæ §O Kim ThiÒn ChØ Hoµn",tbProp={0,5381,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O §¹i To ChØ Hoµn",tbProp={0,5391,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O §¹i Thoa ChØ Hoµn",tbProp={0,5401,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Nh­ u ChØ Hoµn",tbProp={0,5411,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim §µn H­¬ng ChØ Hoµn",tbProp={0,5421,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Long §¶m ChØ Hoµn",tbProp={0,5431,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh Minh Ch©u ChØ Hoµn",tbProp={0,5441,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt L­u Li ChØ Hoµn",tbProp={0,5451,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng TuyOt Ngäc ChØ Hoµn",tbProp={0,5461,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Linh Lung ChØ Hoµn",tbProp={0,5471,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi HuyOt TUch ChØ Hoµn	",tbProp={0,5481,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt HuyÒn ¢m Giíi",tbProp={0,5491,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt Phi Hoa ChØ Hoµn",tbProp={0,5501,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Linh Xµ ChØ Hoµn",tbProp={0,5511,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh NhiOp Ph¸ch ChØ Hoµn",tbProp={0,5521,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long V¹n Tr­îng ChØ Hoµn",tbProp={0,5531,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Lôc Long Ban ChØ",tbProp={0,5541,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt LiÖt DiÔm Ban ChØ	",tbProp={0,5551,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Dong Nham ChØ Hoµn",tbProp={0,5561,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n VÜnh Sinh ChØ Hoµn",tbProp={0,5571,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy H»ng Cöu Ph¸p Giíi",tbProp={0,5581,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i Träng D­¬ng Giíi",tbProp={0,5591,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh Linh Ngäc ChØ Hoµn	",tbProp={0,5601,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Thiªn ThÇn ChØ Hoµn",tbProp={0,5611,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ §~a Vi ChØ Hoµn",tbProp={0,5621,},nQuality=1,},
	},
	[4] =
	{
		{szName="Tinh S­¬ng Khæ §O Hé UyÓn",tbProp={0,5382,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O Hé UyÓn",tbProp={0,5392,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O Hé UyÓn",tbProp={0,5402,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Thóc UyÓn",tbProp={0,5412,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Thóc UyÓn",tbProp={0,5422,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Thóc UyÓn",tbProp={0,5432,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh L­u V©n Tô",tbProp={0,5442,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt TuyOt ¶nh Tô",tbProp={0,5452,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng CÈm Tó Hé UyÓn",tbProp={0,5462,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Sinh Hoa Thñ Tr¹c",tbProp={0,5472,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Hé UyÓn",tbProp={0,5482,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt Hé UyÓn",tbProp={0,5492,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt Hé UyÓn",tbProp={0,5502,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Hé UyÓn",tbProp={0,5512,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh Hé UyÓn",tbProp={0,5522,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long Hé UyÓn",tbProp={0,5532,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Hé UyÓn",tbProp={0,5542,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Hé UyÓn",tbProp={0,5552,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Hé UyÓn",tbProp={0,5562,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n Tô",tbProp={0,5572,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy Tô",tbProp={0,5582,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i Hé UyÓn",tbProp={0,5592,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh Hé UyÓn",tbProp={0,5602,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Hé UyÓn",tbProp={0,5612,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ Hé UyÓn",tbProp={0,5622,},nQuality=1,},
	},
	[5] =
	{
		{szName="Tinh S­¬ng Khæ §O Yªu §¸i",tbProp={0,5383,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O Yªu §¸i",tbProp={0,5393,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O Yªu §¸i",tbProp={0,5403,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Yªu §¸i",tbProp={0,5413,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Yªu §¸i",tbProp={0,5423,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Yªu §¸i",tbProp={0,5433,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh Ti §¸i",tbProp={0,5443,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt Ti §¸i",tbProp={0,5453,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng Yªu §¸i",tbProp={0,5463,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Ti §¸i",tbProp={0,5473,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Yªu §¸i",tbProp={0,5483,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt Yªu §¸i",tbProp={0,5493,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt TriÒn Yªu",tbProp={0,5503,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Thóc Yªu",tbProp={0,5513,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh Thóc Yªu",tbProp={0,5523,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long Thóc Yªu",tbProp={0,5533,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Thóc Yªu",tbProp={0,5543,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Yªu §¸i",tbProp={0,5553,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Yªu §¸i",tbProp={0,5563,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n Ph¸p §¸i",tbProp={0,5573,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy Ph¸p §¸i",tbProp={0,5583,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i Yªu §¸i",tbProp={0,5593,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh Yªu §¸i",tbProp={0,5603,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Yªu §¸i",tbProp={0,5613,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ Yªu §¸i",tbProp={0,5623,},nQuality=1,},
	},
	[6] = 
	{
		{szName="Tinh S­¬ng Khæ §O Cµ Sa",tbProp={0,5384,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O Cµ Sa",tbProp={0,5394,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O Cµ Sa",tbProp={0,5404,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Kh¶i",tbProp={0,5414,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Kh¶i",tbProp={0,5424,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Kh¶i",tbProp={0,5434,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh Nghª Th­êng Vò Y",tbProp={0,5444,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt TuyOt Tiªu Y",tbProp={0,5454,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng Khëi La Sam",tbProp={0,5464,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Th¸i §iÖp Y",tbProp={0,5474,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Cæ Y",tbProp={0,5484,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt Hé Gi¸p",tbProp={0,5494,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt Gi¸p",tbProp={0,5504,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Gi¸p Y",tbProp={0,5514,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh Gi¸p Y",tbProp={0,5524,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long C¸i Y",tbProp={0,5534,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç C¸i Y",tbProp={0,5544,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Gi¸p",tbProp={0,5554,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Gi¸p Y",tbProp={0,5564,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n §¹o Bµo",tbProp={0,5574,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy §¹o Bµo",tbProp={0,5584,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i §¹o Bµo",tbProp={0,5594,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh §¹o Bµo",tbProp={0,5604,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Y",tbProp={0,5614,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ Y",tbProp={0,5624,},nQuality=1,},
	},
	[7] = 
	{
		{szName="Tinh S­¬ng Khæ §O TriÒn Thñ",tbProp={0,5385,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O Ph¸p C«n",tbProp={0,5395,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O Giíi §ao",tbProp={0,5405,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ ThÇn Chïy",tbProp={0,5415,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Th­¬ng",tbProp={0,5425,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng B¶o §ao",tbProp={0,5435,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh B¶o KiÕm",tbProp={0,5445,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt TriÒn Thñ",tbProp={0,5455,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng B¶o §ao",tbProp={0,5465,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Uyªn ¦¬ng §ao",tbProp={0,5475,},nQuality=1,},		
		{szName="Tinh S­¬ng ThiÒm Phi TriÒn Thñ",tbProp={0,5485,},nQuality=1,},		
		{szName="Tinh S­¬ng Phô Cèt HuyOt NhËn",tbProp={0,5495,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt Phi §ao",tbProp={0,5505,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Tô TiÔn",tbProp={0,5515,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh Phi Tiªu",tbProp={0,5525,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long TriÒn Thñ",tbProp={0,5535,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Tr­îng",tbProp={0,5545,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Th­¬ng",tbProp={0,5555,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm B¶o §ao",tbProp={0,5565,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n ThÇn KiÕm",tbProp={0,5575,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy ThÇn KiÕm",tbProp={0,5585,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i B¶o §ao",tbProp={0,5595,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh ThÇn KiÕm",tbProp={0,5605,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn KiÕm",tbProp={0,5615,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ KiÕm",tbProp={0,5625,},nQuality=1,},
	},
	[8] = 
	{
		{szName="Tinh S­¬ng Khæ §O T¨ng Hµi",tbProp={0,5386,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O T¨ng Hµi",tbProp={0,5396,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O T¨ng Hµi",tbProp={0,5406,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Ngoa",tbProp={0,5416,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Ngoa",tbProp={0,5426,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Ngoa",tbProp={0,5436,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh L÷",tbProp={0,5446,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt Ngoa",tbProp={0,5456,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng Ngoa",tbProp={0,5466,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Ngoa",tbProp={0,5476,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Ngoa",tbProp={0,5486,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt Ngoa",tbProp={0,5496,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt L÷",tbProp={0,5506,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn L÷",tbProp={0,5516,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh L÷",tbProp={0,5526,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long Ngoa",tbProp={0,5536,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Ngoa",tbProp={0,5546,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Ngoa",tbProp={0,5556,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Ngoa",tbProp={0,5566,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n L÷",tbProp={0,5576,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy L÷",tbProp={0,5586,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i Ngoa",tbProp={0,5596,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh Ngoa",tbProp={0,5606,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Ngoa",tbProp={0,5616,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ Ngoa",tbProp={0,5626,},nQuality=1,},
	},
	[9] = 
	{
		{szName="Tinh S­¬ng Khæ §O Yªu Trôy",tbProp={0,5387,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O Yªu Trôy",tbProp={0,5397,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O Yªu Trôy",tbProp={0,5407,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Qu¶i Trôy",tbProp={0,5417,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Yªu Trôy",tbProp={0,5427,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Yªu Trôy",tbProp={0,5437,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh H­¬ng Nang",tbProp={0,5447,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt H­¬ng Nang",tbProp={0,5457,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng H­¬ng Nang",tbProp={0,5467,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn H­¬ng Nang",tbProp={0,5477,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Yªu Trôy",tbProp={0,5487,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt Yªu Trôy",tbProp={0,5497,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt Béi",tbProp={0,5507,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Yªu Trôy",tbProp={0,5517,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh Yªu Trôy",tbProp={0,5527,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long Yªu Trôy",tbProp={0,5537,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Yªu Trôy",tbProp={0,5547,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Béi",tbProp={0,5557,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Béi",tbProp={0,5567,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n Ngäc Béi",tbProp={0,5577,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy Ngäc Béi",tbProp={0,5587,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i Béi",tbProp={0,5597,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh Béi",tbProp={0,5607,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn H­¬ng Nang",tbProp={0,5617,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ H­¬ng Nang",tbProp={0,5627,},nQuality=1,},
	},
	[10] = 
	{
		{szName="Tinh S­¬ng Khæ §O HuyÒn Trang ChØ Hoµn",tbProp={0,5388,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O §¹i Bi ChØ Hoµn",tbProp={0,5398,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O TiÓu Thoa ChØ Hoµn",tbProp={0,5408,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ T~ch Tµ ChØ Hoµn",tbProp={0,5418,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim TrÇm H­¬ng ChØ Hoµn",tbProp={0,5428,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Ph­îng T×nh ChØ Hoµn",tbProp={0,5438,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh BUch Ngäc ChØ Hoµn",tbProp={0,5448,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt Thñy Tinh ChØ Hoµn",tbProp={0,5458,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng MÆc Ngäc ChØ Hoµn",tbProp={0,5468,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn San H« ChØ Hoµn",tbProp={0,5478,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Kh« L©u ChØ Hoµn",tbProp={0,5488,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt HuyÒn U Giíi",tbProp={0,5498,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt TrUch DiÖp ChØ Hoµn",tbProp={0,5508,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Kim ThiÒm ChØ Hoµn",tbProp={0,5518,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh §o¹t Hån ChØ Hoµn",tbProp={0,5528,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long Thiªn LU ChØ Hoµn	",tbProp={0,5538,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Linh Th¹ch Ban ChØ",tbProp={0,5548},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt HuyOt Thó Ban ChØ",tbProp={0,5558,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm D­¬ng Viªm ChØ Hoµn",tbProp={0,5568,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n §¹o Hµnh ChØ Hoµn",tbProp={0,5578,},nQuality=1,},
		{szName="KTinh S­¬ng Qu©n Uy BÊt DiÖt Ph¸p Giíi",tbProp={0,5588,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i Cµn Kh«n Giíi",tbProp={0,5598,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh D­¬ng Chi ChØ Hoµn",tbProp={0,5608,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Thiªn C¬ ChØ Hoµn",tbProp={0,5618,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ §~a TUch ChØ Hoµn",tbProp={0,5628,},nQuality=1,},
	},
}


tbRepresentName = 
{
	[1] = "QuyÒn ThiÕu L©m",
	[2] = "C«n ThiÕu L©m",
	[3] = "ThiÕu L©m ®ao",
	[4] = "Chïy Thiªn V­¬ng",
	[5] = "Th­¬ng Thiªn V­¬ng",
	[6] = "§ao Thiªn V­¬ng",
	[7] = "Nga Mi kiÕm",
	[8] = "Nga Mi ch­ëng",
	[9] = "Thóy Yªn ®ao",
	[10] = "ThiÕu Yªn néi",
	[11] = "Ngò §éc ch­ëng",
	[12] = "Ngò §éc ®ao",
	[13] = "§­êng M«n phi ®ao",
	[14] = "§­êng M«n ná",
	[15] = "§­êng M«n tiÓu",
	[16] = "C¸i Bang ch­ëng",
	[17] = "C¸i Bang c«n",
	[18] = "Thiªn NhÉn chiÕn",
	[19] = "Thiªn NhÉn ma",
	[20] = "Vâ §ang khÝ",
	[21] = "Vâ §ang kiÕm",
	[22] = "§ao C«n L«n",
	[23] = "KiÕm C«n L«n",
	[24] = "Hoa S¬n KiÕm",
	[25] = "Hoa S¬n KhÝ",
}