tbEquip_BaiHu = 
{
	[1] = 
	{
		{szName="Tinh S­¬ng Khæ §O Ch©u Liªn",tbProp={0,5379,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O PhËt Ch©u",tbProp={0,5389,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O H¹ng Liªn",tbProp={0,5399,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ H¹ng Liªn",tbProp={0,5409,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim H¹ng Liªn",tbProp={0,5419,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng H¹ng Liªn",tbProp={0,5429,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh Ch©u Liªn",tbProp={0,5439,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt Ch©u Liªn",tbProp={0,5449,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng Ch©u Liªn",tbProp={0,5459,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Ch©u Liªn",tbProp={0,5469,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi H¹ng Liªn",tbProp={0,5479,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt H¹ng Liªn",tbProp={0,5489,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt H¹ng Liªn",tbProp={0,5499,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn H¹ng Liªn",tbProp={0,5509,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh H¹ng Liªn",tbProp={0,5519,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long H¹ng Liªn",tbProp={0,5529,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç H¹ng Liªn",tbProp={0,5539,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt H¹ng QuyÓn",tbProp={0,5549,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm H¹ng Liªn",tbProp={0,5559,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n Phï",tbProp={0,5569,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy Phï",tbProp={0,5579,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i H¹ng Liªn",tbProp={0,5589,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh Phï",tbProp={0,5599,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn H¹ng Liªn",tbProp={0,5609,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ H¹ng Liªn",tbProp={0,5619,},nQuality=1,},
	},
	[2] = 
	{
		{szName="Tinh S­¬ng Khæ §O T¨ng M¹o",tbProp={0,5380,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O T¨ng M¹o",tbProp={0,5390,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O T¨ng M¹o",tbProp={0,5400,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Kh«i",tbProp={0,5410,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Kh«i",tbProp={0,5420,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Kh«i",tbProp={0,5430,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh Ph¸t §¸i",tbProp={0,5440,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt Ph¸t §¸i",tbProp={0,5450,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng Tr©m",tbProp={0,5460,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Tr©m",tbProp={0,5470,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Ph¸t §¸i",tbProp={0,5480,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt Ph¸t §¸i",tbProp={0,5490,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt Qu¸n",tbProp={0,5500,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Qu¸n",tbProp={0,5510,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh Ph¸t Qu¸n",tbProp={0,5520,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long §Çu Hoµn",tbProp={0,5530,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç §Çu Hoµn",tbProp={0,5540,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Kh«i",tbProp={0,5550,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Qu¸n MiÖn",tbProp={0,5560,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n Qu¸n",tbProp={0,5570,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy Qu¸n",tbProp={0,5580,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i §¹o Qu¸n",tbProp={0,5590,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh §¹o Qu¸n",tbProp={0,5600,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Qu¸n",tbProp={0,5610,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ Qu¸n",tbProp={0,5620,},nQuality=1,},
	},
	[3] = 
	{
		{szName="Tinh S­¬ng Khæ §O Kim ThiÒn ChØ Hoµn",tbProp={0,5381,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O §¹i To ChØ Hoµn",tbProp={0,5391,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O §¹i Thoa ChØ Hoµn",tbProp={0,5401,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Nh­ u ChØ Hoµn",tbProp={0,5411,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim §µn H­¬ng ChØ Hoµn",tbProp={0,5421,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Long §¶m ChØ Hoµn",tbProp={0,5431,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh Minh Ch©u ChØ Hoµn",tbProp={0,5441,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt L­u Li ChØ Hoµn",tbProp={0,5451,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng TuyOt Ngäc ChØ Hoµn",tbProp={0,5461,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Linh Lung ChØ Hoµn",tbProp={0,5471,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi HuyOt TUch ChØ Hoµn	",tbProp={0,5481,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt HuyÒn ¢m Giíi",tbProp={0,5491,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt Phi Hoa ChØ Hoµn",tbProp={0,5501,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Linh Xµ ChØ Hoµn",tbProp={0,5511,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh NhiOp Ph¸ch ChØ Hoµn",tbProp={0,5521,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long V¹n Tr­îng ChØ Hoµn",tbProp={0,5531,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Lôc Long Ban ChØ",tbProp={0,5541,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt LiÖt DiÔm Ban ChØ	",tbProp={0,5551,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Dong Nham ChØ Hoµn",tbProp={0,5561,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n VÜnh Sinh ChØ Hoµn",tbProp={0,5571,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy H»ng Cöu Ph¸p Giíi",tbProp={0,5581,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i Träng D­¬ng Giíi",tbProp={0,5591,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh Linh Ngäc ChØ Hoµn	",tbProp={0,5601,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Thiªn ThÇn ChØ Hoµn",tbProp={0,5611,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ §~a Vi ChØ Hoµn",tbProp={0,5621,},nQuality=1,},
	},
	[4] =
	{
		{szName="Tinh S­¬ng Khæ §O Hé UyÓn",tbProp={0,5382,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O Hé UyÓn",tbProp={0,5392,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O Hé UyÓn",tbProp={0,5402,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Thóc UyÓn",tbProp={0,5412,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Thóc UyÓn",tbProp={0,5422,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Thóc UyÓn",tbProp={0,5432,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh L­u V©n Tô",tbProp={0,5442,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt TuyOt ¶nh Tô",tbProp={0,5452,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng CÈm Tó Hé UyÓn",tbProp={0,5462,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Sinh Hoa Thñ Tr¹c",tbProp={0,5472,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Hé UyÓn",tbProp={0,5482,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt Hé UyÓn",tbProp={0,5492,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt Hé UyÓn",tbProp={0,5502,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Hé UyÓn",tbProp={0,5512,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh Hé UyÓn",tbProp={0,5522,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long Hé UyÓn",tbProp={0,5532,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Hé UyÓn",tbProp={0,5542,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Hé UyÓn",tbProp={0,5552,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Hé UyÓn",tbProp={0,5562,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n Tô",tbProp={0,5572,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy Tô",tbProp={0,5582,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i Hé UyÓn",tbProp={0,5592,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh Hé UyÓn",tbProp={0,5602,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Hé UyÓn",tbProp={0,5612,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ Hé UyÓn",tbProp={0,5622,},nQuality=1,},
	},
	[5] =
	{
		{szName="Tinh S­¬ng Khæ §O Yªu §¸i",tbProp={0,5383,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O Yªu §¸i",tbProp={0,5393,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O Yªu §¸i",tbProp={0,5403,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Yªu §¸i",tbProp={0,5413,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Yªu §¸i",tbProp={0,5423,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Yªu §¸i",tbProp={0,5433,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh Ti §¸i",tbProp={0,5443,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt Ti §¸i",tbProp={0,5453,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng Yªu §¸i",tbProp={0,5463,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Ti §¸i",tbProp={0,5473,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Yªu §¸i",tbProp={0,5483,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt Yªu §¸i",tbProp={0,5493,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt TriÒn Yªu",tbProp={0,5503,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Thóc Yªu",tbProp={0,5513,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh Thóc Yªu",tbProp={0,5523,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long Thóc Yªu",tbProp={0,5533,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Thóc Yªu",tbProp={0,5543,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Yªu §¸i",tbProp={0,5553,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Yªu §¸i",tbProp={0,5563,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n Ph¸p §¸i",tbProp={0,5573,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy Ph¸p §¸i",tbProp={0,5583,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i Yªu §¸i",tbProp={0,5593,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh Yªu §¸i",tbProp={0,5603,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Yªu §¸i",tbProp={0,5613,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ Yªu §¸i",tbProp={0,5623,},nQuality=1,},
	},
	[6] = 
	{
		{szName="Tinh S­¬ng Khæ §O Cµ Sa",tbProp={0,5384,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O Cµ Sa",tbProp={0,5394,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O Cµ Sa",tbProp={0,5404,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Kh¶i",tbProp={0,5414,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Kh¶i",tbProp={0,5424,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Kh¶i",tbProp={0,5434,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh Nghª Th­êng Vò Y",tbProp={0,5444,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt TuyOt Tiªu Y",tbProp={0,5454,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng Khëi La Sam",tbProp={0,5464,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Th¸i §iÖp Y",tbProp={0,5474,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Cæ Y",tbProp={0,5484,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt Hé Gi¸p",tbProp={0,5494,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt Gi¸p",tbProp={0,5504,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Gi¸p Y",tbProp={0,5514,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh Gi¸p Y",tbProp={0,5524,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long C¸i Y",tbProp={0,5534,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç C¸i Y",tbProp={0,5544,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Gi¸p",tbProp={0,5554,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Gi¸p Y",tbProp={0,5564,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n §¹o Bµo",tbProp={0,5574,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy §¹o Bµo",tbProp={0,5584,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i §¹o Bµo",tbProp={0,5594,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh §¹o Bµo",tbProp={0,5604,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Y",tbProp={0,5614,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ Y",tbProp={0,5624,},nQuality=1,},
	},
	[7] = 
	{
		{szName="Tinh S­¬ng Khæ §O TriÒn Thñ",tbProp={0,5385,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O Ph¸p C«n",tbProp={0,5395,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O Giíi §ao",tbProp={0,5405,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ ThÇn Chïy",tbProp={0,5415,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Th­¬ng",tbProp={0,5425,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng B¶o §ao",tbProp={0,5435,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh B¶o KiÕm",tbProp={0,5445,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt TriÒn Thñ",tbProp={0,5455,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng B¶o §ao",tbProp={0,5465,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Uyªn ¦¬ng §ao",tbProp={0,5475,},nQuality=1,},		
		{szName="Tinh S­¬ng ThiÒm Phi TriÒn Thñ",tbProp={0,5485,},nQuality=1,},		
		{szName="Tinh S­¬ng Phô Cèt HuyOt NhËn",tbProp={0,5495,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt Phi §ao",tbProp={0,5505,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Tô TiÔn",tbProp={0,5515,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh Phi Tiªu",tbProp={0,5525,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long TriÒn Thñ",tbProp={0,5535,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Tr­îng",tbProp={0,5545,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Th­¬ng",tbProp={0,5555,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm B¶o §ao",tbProp={0,5565,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n ThÇn KiÕm",tbProp={0,5575,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy ThÇn KiÕm",tbProp={0,5585,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i B¶o §ao",tbProp={0,5595,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh ThÇn KiÕm",tbProp={0,5605,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn KiÕm",tbProp={0,5615,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ KiÕm",tbProp={0,5625,},nQuality=1,},
	},
	[8] = 
	{
		{szName="Tinh S­¬ng Khæ §O T¨ng Hµi",tbProp={0,5386,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O T¨ng Hµi",tbProp={0,5396,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O T¨ng Hµi",tbProp={0,5406,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Ngoa",tbProp={0,5416,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Ngoa",tbProp={0,5426,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Ngoa",tbProp={0,5436,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh L÷",tbProp={0,5446,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt Ngoa",tbProp={0,5456,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng Ngoa",tbProp={0,5466,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn Ngoa",tbProp={0,5476,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Ngoa",tbProp={0,5486,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt Ngoa",tbProp={0,5496,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt L÷",tbProp={0,5506,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn L÷",tbProp={0,5516,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh L÷",tbProp={0,5526,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long Ngoa",tbProp={0,5536,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Ngoa",tbProp={0,5546,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Ngoa",tbProp={0,5556,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Ngoa",tbProp={0,5566,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n L÷",tbProp={0,5576,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy L÷",tbProp={0,5586,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i Ngoa",tbProp={0,5596,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh Ngoa",tbProp={0,5606,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Ngoa",tbProp={0,5616,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ Ngoa",tbProp={0,5626,},nQuality=1,},
	},
	[9] = 
	{
		{szName="Tinh S­¬ng Khæ §O Yªu Trôy",tbProp={0,5387,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O Yªu Trôy",tbProp={0,5397,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O Yªu Trôy",tbProp={0,5407,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ Qu¶i Trôy",tbProp={0,5417,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim Yªu Trôy",tbProp={0,5427,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Yªu Trôy",tbProp={0,5437,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh H­¬ng Nang",tbProp={0,5447,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt H­¬ng Nang",tbProp={0,5457,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng H­¬ng Nang",tbProp={0,5467,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn H­¬ng Nang",tbProp={0,5477,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Yªu Trôy",tbProp={0,5487,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt Yªu Trôy",tbProp={0,5497,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt Béi",tbProp={0,5507,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Yªu Trôy",tbProp={0,5517,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh Yªu Trôy",tbProp={0,5527,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long Yªu Trôy",tbProp={0,5537,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Yªu Trôy",tbProp={0,5547,},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt Béi",tbProp={0,5557,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm Béi",tbProp={0,5567,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n Ngäc Béi",tbProp={0,5577,},nQuality=1,},
		{szName="Tinh S­¬ng Qu©n Uy Ngäc Béi",tbProp={0,5587,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i Béi",tbProp={0,5597,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh Béi",tbProp={0,5607,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn H­¬ng Nang",tbProp={0,5617,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ H­¬ng Nang",tbProp={0,5627,},nQuality=1,},
	},
	[10] = 
	{
		{szName="Tinh S­¬ng Khæ §O HuyÒn Trang ChØ Hoµn",tbProp={0,5388,},nQuality=1,},
		{szName="Tinh S­¬ng DiÖt §O §¹i Bi ChØ Hoµn",tbProp={0,5398,},nQuality=1,},
		{szName="Tinh S­¬ng §¹o §O TiÓu Thoa ChØ Hoµn",tbProp={0,5408,},nQuality=1,},
		{szName="Tinh S­¬ng Th«n Tµ T~ch Tµ ChØ Hoµn",tbProp={0,5418,},nQuality=1,},
		{szName="Tinh S­¬ng L­u Kim TrÇm H­¬ng ChØ Hoµn",tbProp={0,5428,},nQuality=1,},
		{szName="Tinh S­¬ng L÷ S­¬ng Ph­îng T×nh ChØ Hoµn",tbProp={0,5438,},nQuality=1,},
		{szName="Tinh S­¬ng L¹c Anh BUch Ngäc ChØ Hoµn",tbProp={0,5448,},nQuality=1,},
		{szName="Tinh S­¬ng PhÊt HuyÖt Thñy Tinh ChØ Hoµn",tbProp={0,5458,},nQuality=1,},
		{szName="Tinh S­¬ng Thiªn H­¬ng MÆc Ngäc ChØ Hoµn",tbProp={0,5468,},nQuality=1,},
		{szName="Tinh S­¬ng Th¸i VËn San H« ChØ Hoµn",tbProp={0,5478,},nQuality=1,},
		{szName="Tinh S­¬ng ThiÒm Phi Kh« L©u ChØ Hoµn",tbProp={0,5488,},nQuality=1,},
		{szName="Tinh S­¬ng Phô Cèt HuyÒn U Giíi",tbProp={0,5498,},nQuality=1,},
		{szName="Tinh S­¬ng L·nh HuyOt TrUch DiÖp ChØ Hoµn",tbProp={0,5508,},nQuality=1,},
		{szName="Tinh S­¬ng Né Liªn Kim ThiÒm ChØ Hoµn",tbProp={0,5518,},nQuality=1,},
		{szName="Tinh S­¬ng Truy MÖnh §o¹t Hån ChØ Hoµn",tbProp={0,5528,},nQuality=1,},
		{szName="Tinh S­¬ng M·nh Long Thiªn LU ChØ Hoµn	",tbProp={0,5538,},nQuality=1,},
		{szName="Tinh S­¬ng Ph¸ Lç Linh Th¹ch Ban ChØ",tbProp={0,5548},nQuality=1,},
		{szName="Tinh S­¬ng LuyÖn NhËt HuyOt Thó Ban ChØ",tbProp={0,5558,},nQuality=1,},
		{szName="Tinh S­¬ng Khèc Viªm D­¬ng Viªm ChØ Hoµn",tbProp={0,5568,},nQuality=1,},
		{szName="Tinh S­¬ng ChÊn S¬n §¹o Hµnh ChØ Hoµn",tbProp={0,5578,},nQuality=1,},
		{szName="KTinh S­¬ng Qu©n Uy BÊt DiÖt Ph¸p Giíi",tbProp={0,5588,},nQuality=1,},
		{szName="Tinh S­¬ng Minh L«i Cµn Kh«n Giíi",tbProp={0,5598,},nQuality=1,},
		{szName="Tinh S­¬ng Oanh Minh D­¬ng Chi ChØ Hoµn",tbProp={0,5608,},nQuality=1,},
		{szName="Tinh S­¬ng H¹o Thiªn Thiªn C¬ ChØ Hoµn",tbProp={0,5618,},nQuality=1,},
		{szName="Tinh S­¬ng Thanh H­ §~a TUch ChØ Hoµn",tbProp={0,5628,},nQuality=1,},
	}
}


tbEquip_JinWuEx = 
{
	[1] = 
	{
		{szName="§»ng Long Bå §Ò Ch©u Liªn",tbProp={0,2975,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai PhËt Ch©u",tbProp={0,2985,},nQuality=1,},
		{szName="§»ng Long V« L­îng H¹ng Liªn",tbProp={0,2995,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn H¹ng Liªn",tbProp={0,3005,},nQuality=1,},
		{szName="§»ng Long T~ch §~a H¹ng Liªn",tbProp={0,3015,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn H¹ng Liªn",tbProp={0,3025,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Ch©u Liªn",tbProp={0,3035,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch Ch©u Liªn",tbProp={0,3045,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Ch©u Liªn",tbProp={0,3055,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Ch©u Liªn",tbProp={0,3065,},nQuality=1,},
		{szName="§»ng Long V¹n §éc H¹ng Liªn",tbProp={0,3075,},nQuality=1,},
		{szName="§»ng Long V¹n Linh H¹ng Liªn",tbProp={0,3085,},nQuality=1,},
		{szName="§»ng Long Hçn §én H¹ng Liªn",tbProp={0,3095,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn H¹ng Liªn",tbProp={0,3105,},nQuality=1,},
		{szName="§»ng Long Phong B¹o H¹ng Liªn",tbProp={0,3115,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh H¹ng Liªn",tbProp={0,3125,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa H¹ng Liªn",tbProp={0,3135,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng H¹ng Khuyªn",tbProp={0,3145,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn H¹ng Liªn",tbProp={0,3155,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Phï",tbProp={0,3165,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Phï",tbProp={0,3175,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn H¹ng Liªn",tbProp={0,3185,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Phï",tbProp={0,3195,},nQuality=1,},
		{szName="§»ng Long Tè Du H¹ng Liªn",tbProp={0,4813,},nQuality=1,},
		{szName="§»ng Long Y Thñy H¹ng Liªn",tbProp={0,4823,},nQuality=1,},

	},
	[2] = 
	{
		{szName="§»ng Long Bå §Ò T¨ng M¹o",tbProp={0,2976,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai T¨ng M¹o",tbProp={0,2986,},nQuality=1,},
		{szName="§»ng Long V« L­îng T¨ng M¹o",tbProp={0,2996,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Kh«i",tbProp={0,3006,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Kh«i",tbProp={0,3016,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Kh«i",tbProp={0,3026,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Ph¸t §¸i",tbProp={0,3036,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch Ph¸t §¸i",tbProp={0,3046,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Tr©m",tbProp={0,3056,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Tr©m",tbProp={0,3066,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Ph¸t §¸i",tbProp={0,3076,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Ph¸t §¸i",tbProp={0,3086,},nQuality=1,},
		{szName="§»ng Long Hçn §én Qu¸n",tbProp={0,3096,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Qu¸n",tbProp={0,3106,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Ph¸t Qu¸n",tbProp={0,3116,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh §Çu Hoµn",tbProp={0,3126,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa §Çu Hoµn",tbProp={0,3136,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Kh«i",tbProp={0,3146,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Qu¸n MiÖn",tbProp={0,3156,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Qu¸n",tbProp={0,3166,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Qu¸n",tbProp={0,3176,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn §¹o Qu¸n",tbProp={0,3186,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung §¹o Qu¸n",tbProp={0,3196,},nQuality=1,},
		{szName="§»ng Long Tè Du Qu¸n",tbProp={0,4814,},nQuality=1,},
		{szName="§»ng Long Y Thñy Qu¸n",tbProp={0,4824,},nQuality=1,},
	},
	[3] = 
	{
		{szName="§»ng Long Bå §Ò Kim ThiÒn ChØ Hoµn",tbProp={0,2977,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai §¹i To ChØ Hoµn",tbProp={0,2987,},nQuality=1,},
		{szName="§»ng Long V« L­îng §¹i Thoa ChØ Hoµn",tbProp={0,2997,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Nh­ u ChØ Hoµn",tbProp={0,3007,},nQuality=1,},
		{szName="§»ng Long T~ch §~a ChØ Hoµn",tbProp={0,3017,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn ChØ Hoµn",tbProp={0,3027,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Minh Ch©u ChØ Hoµn",tbProp={0,3037,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch L­u Ly ChØ Hoµn",tbProp={0,3047,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh TuyOt Ngäc ChØ Hoµn",tbProp={0,3057,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Linh Lung ChØ Hoµn",tbProp={0,3067,},nQuality=1,},
		{szName="§»ng Long V¹n §éc HuyOt TrUch ChØ Hoµn",tbProp={0,3077,},nQuality=1,},
		{szName="§»ng Long V¹n Linh HuyÒn ¢m Giíi",tbProp={0,3087,},nQuality=1,},
		{szName="§»ng Long Hçn §én Phi Hoa ChØ Hoµn",tbProp={0,3097,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Linh Xµ ChØ Hoµn",tbProp={0,3107,},nQuality=1,},
		{szName="§»ng Long Phong B¹o NhiOp Ph¸ch ChØ Hoµn",tbProp={0,3117,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh V¹n Tr­îng ChØ Hoµn",tbProp={0,3127,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Lôc Long Bµn ChØ",tbProp={0,3137,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng LiÖt DiÖm Bµn ChØ",tbProp={0,3147,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Dung Nham ChØ Hoµn",tbProp={0,3157,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ VÜnh Sinh ChØ Hoµn",tbProp={0,3167,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn H»ng Cöu Ph¸p Giíi",tbProp={0,3177,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Trïng D­¬ng Giíi",tbProp={0,3187,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Linh Ngäc ChØ Hoµn",tbProp={0,3197,},nQuality=1,},
		{szName="§»ng Long Tè Du Th­îng Giíi",tbProp={0,4815,},nQuality=1,},
		{szName="§»ng Long Y Thñy Th­îng Giíi",tbProp={0,4825,},nQuality=1,},
	},
	[4] = 
	{
		{szName="§»ng Long Bå §Ò Hé UyÓn",tbProp={0,2978,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Hé UyÓn",tbProp={0,2988,},nQuality=1,},
		{szName="§»ng Long V« L­îng Hé UyÓn",tbProp={0,2998,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Thóc UyÓn",tbProp={0,3008,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Thóc UyÓn",tbProp={0,3018,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Thóc UyÓn",tbProp={0,3028,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn L­u V©n Tô",tbProp={0,3038,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch TuyOt ¶nh Tô",tbProp={0,3048,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh CÈm Tó Hé UyÓn",tbProp={0,3058,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Sinh Hoa Thñ Tr¹c",tbProp={0,3068,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Hé UyÓn",tbProp={0,3078,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Hé UyÓn",tbProp={0,3088,},nQuality=1,},
		{szName="§»ng Long Hçn §én Hé UyÓn",tbProp={0,3098,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Hé UyÓn",tbProp={0,3108,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Hé UyÓn",tbProp={0,3118,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Hé UyÓn",tbProp={0,3128,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Hé UyÓn",tbProp={0,3138,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Hé UyÓn",tbProp={0,3148,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Hé UyÓn",tbProp={0,3158,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Tô",tbProp={0,3168,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Tô",tbProp={0,3178,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Hé UyÓn",tbProp={0,3188,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Hé UyÓn",tbProp={0,3198,},nQuality=1,},
		{szName="§»ng Long Tè Du Hé UyÓn",tbProp={0,4816,},nQuality=1,},
		{szName="§»ng Long Y Thñy Hé UyÓn",tbProp={0,4826,},nQuality=1,},
	},
	[5] = 
	{
		{szName="§»ng Long Bå §Ò Yªu §¸i",tbProp={0,2979,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Yªu §¸i",tbProp={0,2989,},nQuality=1,},
		{szName="§»ng Long V« L­îng Yªu §¸i",tbProp={0,2999,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Yªu §¸i",tbProp={0,3009,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Yªu §¸i",tbProp={0,3019,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Yªu §¸i",tbProp={0,3029,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Ti §¸i",tbProp={0,3039,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch Ti §¸i",tbProp={0,3049,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Yªu §¸i",tbProp={0,3059,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Ti §¸i",tbProp={0,3069,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Yªu §¸i",tbProp={0,3079,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Yªu §¸i",tbProp={0,3089,},nQuality=1,},
		{szName="§»ng Long Hçn §én TriÒn Yªu",tbProp={0,3099,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Thóc Yªu",tbProp={0,3109,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Thóc Yªu",tbProp={0,3119,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Thóc Yªu",tbProp={0,3129,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Thóc Yªu",tbProp={0,3139,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Yªu §¸i",tbProp={0,3149,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Yªu §¸i",tbProp={0,3159,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Ph¸p §¸i",tbProp={0,3169,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Ph¸p §¸i",tbProp={0,3179,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Yªu §¸i",tbProp={0,3189,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Yªu §¸i",tbProp={0,3199,},nQuality=1,},
		{szName="§»ng Long Tè Du Yªu §¸i",tbProp={0,4817,},nQuality=1,},
		{szName="§»ng Long Y Thñy Yªu §¸i",tbProp={0,4827,},nQuality=1,},

	},
	[6] = 
	{
		{szName="§»ng Long Bå §Ò Cµ Sa",tbProp={0,2980,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Cµ Sa",tbProp={0,2990,},nQuality=1,},
		{szName="§»ng Long V« L­îng Cµ Sa",tbProp={0,3000,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Kh¶i",tbProp={0,3010,},nQuality=1,},
		{szName="§»ng Long TÞch §Þa Kh¶i",tbProp={0,3020,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Kh¶i",tbProp={0,3030,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Nghª Th­êng Vò Y",tbProp={0,3040,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch TuyÕt Tiªu Y",tbProp={0,3050,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Khëi La Sam",tbProp={0,3060,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Th¸i §iÖp Y",tbProp={0,3070,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Cæ Y",tbProp={0,3080,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Hé Gi¸p",tbProp={0,3090,},nQuality=1,},
		{szName="§»ng Long Hçn §én Gi¸p",tbProp={0,3100,},nQuality=1,},
		{szName="§»ng Long ThÝ ThÇn Gi¸p Y",tbProp={0,3110,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Gi¸p Y",tbProp={0,3120,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh C¸i Y",tbProp={0,3130,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa C¸i Y",tbProp={0,3140,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Gi¸p",tbProp={0,3150,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Gi¸p Y",tbProp={0,3160,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ §¹o Bµo",tbProp={0,3170,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn §¹o Bµo",tbProp={0,3180,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn §¹o Bµo",tbProp={0,3190,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung §¹o Bµo",tbProp={0,3200,},nQuality=1,},
		{szName="§»ng Long Tè Du Y",tbProp={0,4818,},nQuality=1,},
		{szName="§»ng Long Y Thñy Y",tbProp={0,4828,},nQuality=1,},

	},
	[7] = 
	{
		{szName="§»ng Long Bå §Ò TriÒn Thñ",tbProp={0,2981,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Ph¸p C«n",tbProp={0,2991,},nQuality=1,},
		{szName="§»ng Long V« L­îng Giíi §ao",tbProp={0,3001,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn ThÇn Chïy",tbProp={0,3011,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Th­¬ng",tbProp={0,3021,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn B¶o §ao",tbProp={0,3031,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn B¶o KiÕm",tbProp={0,3041,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch TriÒn Thñ",tbProp={0,3051,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh B¶o §ao",tbProp={0,3061,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Uyªn ¦¬ng §ao",tbProp={0,3071,},nQuality=1,},
		{szName="§»ng Long V¹n §éc TriÒn Thñ",tbProp={0,3081,},nQuality=1,},
		{szName="§»ng Long V¹n Linh HuyOt NhÉn",tbProp={0,3091,},nQuality=1,},
		{szName="§»ng Long Hçn §én Phi §ao",tbProp={0,3101,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Tô TiÔn",tbProp={0,3111,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Phi Tiªu",tbProp={0,3121,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh TriÒn Thñ",tbProp={0,3131,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Tr­îng",tbProp={0,3141,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Th­¬ng",tbProp={0,3151,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn B¶o §ao",tbProp={0,3161,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ ThÇn KiÕm",tbProp={0,3171,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn ThÇn KiÕm",tbProp={0,3181,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn B¶o §ao",tbProp={0,3191,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung ThÇn KiÕm",tbProp={0,3201,},nQuality=1,},
		{szName="§»ng Long Tè Du KiÕm",tbProp={0,4819,},nQuality=1,},
		{szName="§»ng Long Y Thñy KiÕm",tbProp={0,4829,},nQuality=1,},
	},
	[8] = 
	{
		{szName="§»ng Long Bå §Ò T¨ng Hµi",tbProp={0,2982,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai T¨ng Hµi",tbProp={0,2992,},nQuality=1,},
		{szName="§»ng Long V« L­îng T¨ng Hµi",tbProp={0,3002,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Ngoa",tbProp={0,3012,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Ngoa",tbProp={0,3022,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Ngoa",tbProp={0,3032,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Lu",tbProp={0,3042,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch Ngoa",tbProp={0,3052,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Ngoa",tbProp={0,3062,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Ngoa",tbProp={0,3072,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Ngoa",tbProp={0,3082,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Ngoa",tbProp={0,3092,},nQuality=1,},
		{szName="§»ng Long Hçn §én Lu",tbProp={0,3102,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Lu",tbProp={0,3112,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Lu",tbProp={0,3122,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Ngoa",tbProp={0,3132,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Ngoa",tbProp={0,3142,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Ngoa",tbProp={0,3152,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Ngoa",tbProp={0,3162,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Lu",tbProp={0,3172,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Lu",tbProp={0,3182,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Ngoa",tbProp={0,3192,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Ngoa",tbProp={0,3202,},nQuality=1,},
		{szName="§»ng Long Tè Du Hµi",tbProp={0,4820,},nQuality=1,},
		{szName="§»ng Long Y Thñy Hµi",tbProp={0,4830,},nQuality=1,},
	},
	[9] = 
	{
		{szName="§»ng Long Bå §Ò Yªu Trôy",tbProp={0,2983,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Yªu Trôy",tbProp={0,2993,},nQuality=1,},
		{szName="§»ng Long V« L­îng Yªu Trôy",tbProp={0,3003,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Qua Chïy",tbProp={0,3013,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Yªu Trôy",tbProp={0,3023,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Yªu Trôy",tbProp={0,3033,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn H­¬ng Nang",tbProp={0,3043,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch H­¬ng Nang",tbProp={0,3053,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh H­¬ng Nang",tbProp={0,3063,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng H­¬ng Nang",tbProp={0,3073,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Yªu Trôy",tbProp={0,3083,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Yªu Trôy",tbProp={0,3093,},nQuality=1,},
		{szName="§»ng Long Hçn §én Béi",tbProp={0,3103,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Yªu Trôy",tbProp={0,3113,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Yªu Trôy",tbProp={0,3123,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Yªu Trôy",tbProp={0,3133,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Yªu Trôy",tbProp={0,3143,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Béi",tbProp={0,3153,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Béi",tbProp={0,3163,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Ngäc Béi",tbProp={0,3173,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Ngäc Béi",tbProp={0,3183,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Béi",tbProp={0,3193,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Béi",tbProp={0,3203,},nQuality=1,},
		{szName="§»ng Long Tè Du H­¬ng Nang",tbProp={0,4821,},nQuality=1,},
		{szName="§»ng Long Y Thñy H­¬ng Nang",tbProp={0,4831,},nQuality=1,},
	},
	[10] = 
	{
		{szName="§»ng Long Bå §Ò HuyÒn Trang ChØ Hoµn",tbProp={0,2984,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai §¹i Bi ChØ Hoµn",tbProp={0,2994,},nQuality=1,},
		{szName="§»ng Long V« L­îng Tiªu Thoa ChØ Hoµn",tbProp={0,3004,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn T~ch Tµ ChØ Hoµn",tbProp={0,3014,},nQuality=1,},
		{szName="§»ng Long T~ch §~a TrÇm H­¬ng ChØ Hoµn",tbProp={0,3024,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Phông Tinh ChØ Hoµn",tbProp={0,3034,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn BUch Ngäc ChØ Hoµn",tbProp={0,3044,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch B¨ng Tinh ChØ Hoµn",tbProp={0,3054,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh MÆc Ngäc ChØ Hoµn",tbProp={0,3064,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng San H« ChØ Hoµn",tbProp={0,3074,},nQuality=1,},
		{szName="§»ng Long V¹n §éc C« L©u ChØ Hoµn",tbProp={0,3084,},nQuality=1,},
		{szName="§»ng Long V¹n Linh HuyÒn U Giíi",tbProp={0,3094,},nQuality=1,},
		{szName="§»ng Long Hçn §én TrUch DiÖp ChØ Hoµn",tbProp={0,3104,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Kim ThiÒm ChØ Hoµn",tbProp={0,3114,},nQuality=1,},
		{szName="§»ng Long Phong B¹o §o¹t Hån ChØ Hoµn",tbProp={0,3124,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Thiªn Lu ChØ Hoµn",tbProp={0,3134,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Linh Ngäc Bµn ChØ",tbProp={0,3144,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng HuyOt Thó Bµn ChØ",tbProp={0,3154,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn D­¬ng Viªm ChØ Hoµn",tbProp={0,3164,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ §¹o Hµnh ChØ Hoµn",tbProp={0,3174,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn BÊt DiÖt Ph¸p Giíi",tbProp={0,3184,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Cµn Kh«n Giíi",tbProp={0,3194,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung D­¬ng Chi ChØ Hoµn",tbProp={0,3204,},nQuality=1,},
		{szName="§»ng Long Tè Du H¹ Giíi",tbProp={0,4822,},nQuality=1,},
		{szName="§»ng Long Y Thñy H¹ Giíi",tbProp={0,4832,},nQuality=1,},
	},
}