tbEquip_BaiHu = 
{
		[1] = 
	{
		{szName="§»ng Long Bå §Ò Ch©u Liªn",tbProp={0,2975,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai PhËt Ch©u",tbProp={0,2985,},nQuality=1,},
		{szName="§»ng Long V« L­îng H¹ng Liªn",tbProp={0,2995,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn H¹ng Liªn",tbProp={0,3005,},nQuality=1,},
		{szName="§»ng Long T~ch §~a H¹ng Liªn",tbProp={0,3015,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn H¹ng Liªn",tbProp={0,3025,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Ch©u Liªn",tbProp={0,3035,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch Ch©u Liªn",tbProp={0,3045,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Ch©u Liªn",tbProp={0,3055,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Ch©u Liªn",tbProp={0,3065,},nQuality=1,},
		{szName="§»ng Long V¹n §éc H¹ng Liªn",tbProp={0,3075,},nQuality=1,},
		{szName="§»ng Long V¹n Linh H¹ng Liªn",tbProp={0,3085,},nQuality=1,},
		{szName="§»ng Long Hçn §én H¹ng Liªn",tbProp={0,3095,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn H¹ng Liªn",tbProp={0,3105,},nQuality=1,},
		{szName="§»ng Long Phong B¹o H¹ng Liªn",tbProp={0,3115,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh H¹ng Liªn",tbProp={0,3125,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa H¹ng Liªn",tbProp={0,3135,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng H¹ng Khuyªn",tbProp={0,3145,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn H¹ng Liªn",tbProp={0,3155,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Phï",tbProp={0,3165,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Phï",tbProp={0,3175,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn H¹ng Liªn",tbProp={0,3185,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Phï",tbProp={0,3195,},nQuality=1,},
		{szName="§»ng Long Tè Du H¹ng Liªn",tbProp={0,4813,},nQuality=1,},
		{szName="§»ng Long Y Thñy H¹ng Liªn",tbProp={0,4823,},nQuality=1,},

	},
	[2] = 
	{
		{szName="§»ng Long Bå §Ò T¨ng M¹o",tbProp={0,2976,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai T¨ng M¹o",tbProp={0,2986,},nQuality=1,},
		{szName="§»ng Long V« L­îng T¨ng M¹o",tbProp={0,2996,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Kh«i",tbProp={0,3006,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Kh«i",tbProp={0,3016,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Kh«i",tbProp={0,3026,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Ph¸t §¸i",tbProp={0,3036,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch Ph¸t §¸i",tbProp={0,3046,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Tr©m",tbProp={0,3056,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Tr©m",tbProp={0,3066,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Ph¸t §¸i",tbProp={0,3076,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Ph¸t §¸i",tbProp={0,3086,},nQuality=1,},
		{szName="§»ng Long Hçn §én Qu¸n",tbProp={0,3096,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Qu¸n",tbProp={0,3106,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Ph¸t Qu¸n",tbProp={0,3116,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh §Çu Hoµn",tbProp={0,3126,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa §Çu Hoµn",tbProp={0,3136,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Kh«i",tbProp={0,3146,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Qu¸n MiÖn",tbProp={0,3156,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Qu¸n",tbProp={0,3166,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Qu¸n",tbProp={0,3176,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn §¹o Qu¸n",tbProp={0,3186,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung §¹o Qu¸n",tbProp={0,3196,},nQuality=1,},
		{szName="§»ng Long Tè Du Qu¸n",tbProp={0,4814,},nQuality=1,},
		{szName="§»ng Long Y Thñy Qu¸n",tbProp={0,4824,},nQuality=1,},
	},
	[3] = 
	{
		{szName="§»ng Long Bå §Ò Kim ThiÒn ChØ Hoµn",tbProp={0,2977,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai §¹i To ChØ Hoµn",tbProp={0,2987,},nQuality=1,},
		{szName="§»ng Long V« L­îng §¹i Thoa ChØ Hoµn",tbProp={0,2997,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Nh­ u ChØ Hoµn",tbProp={0,3007,},nQuality=1,},
		{szName="§»ng Long T~ch §~a ChØ Hoµn",tbProp={0,3017,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn ChØ Hoµn",tbProp={0,3027,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Minh Ch©u ChØ Hoµn",tbProp={0,3037,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch L­u Ly ChØ Hoµn",tbProp={0,3047,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh TuyOt Ngäc ChØ Hoµn",tbProp={0,3057,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Linh Lung ChØ Hoµn",tbProp={0,3067,},nQuality=1,},
		{szName="§»ng Long V¹n §éc HuyOt TrUch ChØ Hoµn",tbProp={0,3077,},nQuality=1,},
		{szName="§»ng Long V¹n Linh HuyÒn ¢m Giíi",tbProp={0,3087,},nQuality=1,},
		{szName="§»ng Long Hçn §én Phi Hoa ChØ Hoµn",tbProp={0,3097,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Linh Xµ ChØ Hoµn",tbProp={0,3107,},nQuality=1,},
		{szName="§»ng Long Phong B¹o NhiOp Ph¸ch ChØ Hoµn",tbProp={0,3117,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh V¹n Tr­îng ChØ Hoµn",tbProp={0,3127,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Lôc Long Bµn ChØ",tbProp={0,3137,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng LiÖt DiÖm Bµn ChØ",tbProp={0,3147,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Dung Nham ChØ Hoµn",tbProp={0,3157,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ VÜnh Sinh ChØ Hoµn",tbProp={0,3167,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn H»ng Cöu Ph¸p Giíi",tbProp={0,3177,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Trïng D­¬ng Giíi",tbProp={0,3187,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Linh Ngäc ChØ Hoµn",tbProp={0,3197,},nQuality=1,},
		{szName="§»ng Long Tè Du Th­îng Giíi",tbProp={0,4815,},nQuality=1,},
		{szName="§»ng Long Y Thñy Th­îng Giíi",tbProp={0,4825,},nQuality=1,},
	},
	[4] = 
	{
		{szName="§»ng Long Bå §Ò Hé UyÓn",tbProp={0,2978,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Hé UyÓn",tbProp={0,2988,},nQuality=1,},
		{szName="§»ng Long V« L­îng Hé UyÓn",tbProp={0,2998,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Thóc UyÓn",tbProp={0,3008,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Thóc UyÓn",tbProp={0,3018,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Thóc UyÓn",tbProp={0,3028,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn L­u V©n Tô",tbProp={0,3038,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch TuyOt ¶nh Tô",tbProp={0,3048,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh CÈm Tó Hé UyÓn",tbProp={0,3058,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Sinh Hoa Thñ Tr¹c",tbProp={0,3068,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Hé UyÓn",tbProp={0,3078,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Hé UyÓn",tbProp={0,3088,},nQuality=1,},
		{szName="§»ng Long Hçn §én Hé UyÓn",tbProp={0,3098,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Hé UyÓn",tbProp={0,3108,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Hé UyÓn",tbProp={0,3118,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Hé UyÓn",tbProp={0,3128,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Hé UyÓn",tbProp={0,3138,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Hé UyÓn",tbProp={0,3148,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Hé UyÓn",tbProp={0,3158,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Tô",tbProp={0,3168,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Tô",tbProp={0,3178,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Hé UyÓn",tbProp={0,3188,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Hé UyÓn",tbProp={0,3198,},nQuality=1,},
		{szName="§»ng Long Tè Du Hé UyÓn",tbProp={0,4816,},nQuality=1,},
		{szName="§»ng Long Y Thñy Hé UyÓn",tbProp={0,4826,},nQuality=1,},
	},
	[5] = 
	{
		{szName="§»ng Long Bå §Ò Yªu §¸i",tbProp={0,2979,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Yªu §¸i",tbProp={0,2989,},nQuality=1,},
		{szName="§»ng Long V« L­îng Yªu §¸i",tbProp={0,2999,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Yªu §¸i",tbProp={0,3009,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Yªu §¸i",tbProp={0,3019,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Yªu §¸i",tbProp={0,3029,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Ti §¸i",tbProp={0,3039,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch Ti §¸i",tbProp={0,3049,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Yªu §¸i",tbProp={0,3059,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Ti §¸i",tbProp={0,3069,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Yªu §¸i",tbProp={0,3079,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Yªu §¸i",tbProp={0,3089,},nQuality=1,},
		{szName="§»ng Long Hçn §én TriÒn Yªu",tbProp={0,3099,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Thóc Yªu",tbProp={0,3109,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Thóc Yªu",tbProp={0,3119,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Thóc Yªu",tbProp={0,3129,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Thóc Yªu",tbProp={0,3139,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Yªu §¸i",tbProp={0,3149,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Yªu §¸i",tbProp={0,3159,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Ph¸p §¸i",tbProp={0,3169,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Ph¸p §¸i",tbProp={0,3179,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Yªu §¸i",tbProp={0,3189,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Yªu §¸i",tbProp={0,3199,},nQuality=1,},
		{szName="§»ng Long Tè Du Yªu §¸i",tbProp={0,4817,},nQuality=1,},
		{szName="§»ng Long Y Thñy Yªu §¸i",tbProp={0,4827,},nQuality=1,},

	},
	[6] = 
	{
		{szName="§»ng Long Bå §Ò Cµ Sa",tbProp={0,2980,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Cµ Sa",tbProp={0,2990,},nQuality=1,},
		{szName="§»ng Long V« L­îng Cµ Sa",tbProp={0,3000,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Kh¶i",tbProp={0,3010,},nQuality=1,},
		{szName="§»ng Long TÞch §Þa Kh¶i",tbProp={0,3020,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Kh¶i",tbProp={0,3030,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Nghª Th­êng Vò Y",tbProp={0,3040,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch TuyÕt Tiªu Y",tbProp={0,3050,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Khëi La Sam",tbProp={0,3060,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Th¸i §iÖp Y",tbProp={0,3070,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Cæ Y",tbProp={0,3080,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Hé Gi¸p",tbProp={0,3090,},nQuality=1,},
		{szName="§»ng Long Hçn §én Gi¸p",tbProp={0,3100,},nQuality=1,},
		{szName="§»ng Long ThÝ ThÇn Gi¸p Y",tbProp={0,3110,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Gi¸p Y",tbProp={0,3120,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh C¸i Y",tbProp={0,3130,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa C¸i Y",tbProp={0,3140,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Gi¸p",tbProp={0,3150,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Gi¸p Y",tbProp={0,3160,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ §¹o Bµo",tbProp={0,3170,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn §¹o Bµo",tbProp={0,3180,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn §¹o Bµo",tbProp={0,3190,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung §¹o Bµo",tbProp={0,3200,},nQuality=1,},
		{szName="§»ng Long Tè Du Y",tbProp={0,4818,},nQuality=1,},
		{szName="§»ng Long Y Thñy Y",tbProp={0,4828,},nQuality=1,},

	},
	[7] = 
	{
		{szName="§»ng Long Bå §Ò TriÒn Thñ",tbProp={0,2981,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Ph¸p C«n",tbProp={0,2991,},nQuality=1,},
		{szName="§»ng Long V« L­îng Giíi §ao",tbProp={0,3001,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn ThÇn Chïy",tbProp={0,3011,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Th­¬ng",tbProp={0,3021,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn B¶o §ao",tbProp={0,3031,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn B¶o KiÕm",tbProp={0,3041,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch TriÒn Thñ",tbProp={0,3051,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh B¶o §ao",tbProp={0,3061,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Uyªn ¦¬ng §ao",tbProp={0,3071,},nQuality=1,},
		{szName="§»ng Long V¹n §éc TriÒn Thñ",tbProp={0,3081,},nQuality=1,},
		{szName="§»ng Long V¹n Linh HuyOt NhÉn",tbProp={0,3091,},nQuality=1,},
		{szName="§»ng Long Hçn §én Phi §ao",tbProp={0,3101,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Tô TiÔn",tbProp={0,3111,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Phi Tiªu",tbProp={0,3121,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh TriÒn Thñ",tbProp={0,3131,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Tr­îng",tbProp={0,3141,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Th­¬ng",tbProp={0,3151,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn B¶o §ao",tbProp={0,3161,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ ThÇn KiÕm",tbProp={0,3171,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn ThÇn KiÕm",tbProp={0,3181,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn B¶o §ao",tbProp={0,3191,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung ThÇn KiÕm",tbProp={0,3201,},nQuality=1,},
		{szName="§»ng Long Tè Du KiÕm",tbProp={0,4819,},nQuality=1,},
		{szName="§»ng Long Y Thñy KiÕm",tbProp={0,4829,},nQuality=1,},
	},
	[8] = 
	{
		{szName="§»ng Long Bå §Ò T¨ng Hµi",tbProp={0,2982,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai T¨ng Hµi",tbProp={0,2992,},nQuality=1,},
		{szName="§»ng Long V« L­îng T¨ng Hµi",tbProp={0,3002,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Ngoa",tbProp={0,3012,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Ngoa",tbProp={0,3022,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Ngoa",tbProp={0,3032,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn Lu",tbProp={0,3042,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch Ngoa",tbProp={0,3052,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh Ngoa",tbProp={0,3062,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng Ngoa",tbProp={0,3072,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Ngoa",tbProp={0,3082,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Ngoa",tbProp={0,3092,},nQuality=1,},
		{szName="§»ng Long Hçn §én Lu",tbProp={0,3102,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Lu",tbProp={0,3112,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Lu",tbProp={0,3122,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Ngoa",tbProp={0,3132,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Ngoa",tbProp={0,3142,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Ngoa",tbProp={0,3152,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Ngoa",tbProp={0,3162,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Lu",tbProp={0,3172,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Lu",tbProp={0,3182,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Ngoa",tbProp={0,3192,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Ngoa",tbProp={0,3202,},nQuality=1,},
		{szName="§»ng Long Tè Du Hµi",tbProp={0,4820,},nQuality=1,},
		{szName="§»ng Long Y Thñy Hµi",tbProp={0,4830,},nQuality=1,},
	},
	[9] = 
	{
		{szName="§»ng Long Bå §Ò Yªu Trôy",tbProp={0,2983,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai Yªu Trôy",tbProp={0,2993,},nQuality=1,},
		{szName="§»ng Long V« L­îng Yªu Trôy",tbProp={0,3003,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn Qua Chïy",tbProp={0,3013,},nQuality=1,},
		{szName="§»ng Long T~ch §~a Yªu Trôy",tbProp={0,3023,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Yªu Trôy",tbProp={0,3033,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn H­¬ng Nang",tbProp={0,3043,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch H­¬ng Nang",tbProp={0,3053,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh H­¬ng Nang",tbProp={0,3063,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng H­¬ng Nang",tbProp={0,3073,},nQuality=1,},
		{szName="§»ng Long V¹n §éc Yªu Trôy",tbProp={0,3083,},nQuality=1,},
		{szName="§»ng Long V¹n Linh Yªu Trôy",tbProp={0,3093,},nQuality=1,},
		{szName="§»ng Long Hçn §én Béi",tbProp={0,3103,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Yªu Trôy",tbProp={0,3113,},nQuality=1,},
		{szName="§»ng Long Phong B¹o Yªu Trôy",tbProp={0,3123,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Yªu Trôy",tbProp={0,3133,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Yªu Trôy",tbProp={0,3143,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng Béi",tbProp={0,3153,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn Béi",tbProp={0,3163,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ Ngäc Béi",tbProp={0,3173,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn Ngäc Béi",tbProp={0,3183,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Béi",tbProp={0,3193,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung Béi",tbProp={0,3203,},nQuality=1,},
		{szName="§»ng Long Tè Du H­¬ng Nang",tbProp={0,4821,},nQuality=1,},
		{szName="§»ng Long Y Thñy H­¬ng Nang",tbProp={0,4831,},nQuality=1,},
	},
	[10] = 
	{
		{szName="§»ng Long Bå §Ò HuyÒn Trang ChØ Hoµn",tbProp={0,2984,},nQuality=1,},
		{szName="§»ng Long Nh­ Lai §¹i Bi ChØ Hoµn",tbProp={0,2994,},nQuality=1,},
		{szName="§»ng Long V« L­îng Tiªu Thoa ChØ Hoµn",tbProp={0,3004,},nQuality=1,},
		{szName="§»ng Long Khai Thiªn T~ch Tµ ChØ Hoµn",tbProp={0,3014,},nQuality=1,},
		{szName="§»ng Long T~ch §~a TrÇm H­¬ng ChØ Hoµn",tbProp={0,3024,},nQuality=1,},
		{szName="§»ng Long Hçn Nguyªn Phông Tinh ChØ Hoµn",tbProp={0,3034,},nQuality=1,},
		{szName="§»ng Long Phi Thiªn BUch Ngäc ChØ Hoµn",tbProp={0,3044,},nQuality=1,},
		{szName="§»ng Long B¨ng Ph¸ch B¨ng Tinh ChØ Hoµn",tbProp={0,3054,},nQuality=1,},
		{szName="§»ng Long Khuynh Thµnh MÆc Ngäc ChØ Hoµn",tbProp={0,3064,},nQuality=1,},
		{szName="§»ng Long B¸ch H­¬ng San H« ChØ Hoµn",tbProp={0,3074,},nQuality=1,},
		{szName="§»ng Long V¹n §éc C« L©u ChØ Hoµn",tbProp={0,3084,},nQuality=1,},
		{szName="§»ng Long V¹n Linh HuyÒn U Giíi",tbProp={0,3094,},nQuality=1,},
		{szName="§»ng Long Hçn §én TrUch DiÖp ChØ Hoµn",tbProp={0,3104,},nQuality=1,},
		{szName="§»ng Long ThU ThÇn Kim ThiÒm ChØ Hoµn",tbProp={0,3114,},nQuality=1,},
		{szName="§»ng Long Phong B¹o §o¹t Hån ChØ Hoµn",tbProp={0,3124,},nQuality=1,},
		{szName="§»ng Long Hµo T×nh Thiªn Lu ChØ Hoµn",tbProp={0,3134,},nQuality=1,},
		{szName="§»ng Long Tô NghÜa Linh Ngäc Bµn ChØ",tbProp={0,3144,},nQuality=1,},
		{szName="§»ng Long Viªm Hoµng HuyOt Thó Bµn ChØ",tbProp={0,3154,},nQuality=1,},
		{szName="§»ng Long PhÇn Thiªn D­¬ng Viªm ChØ Hoµn",tbProp={0,3164,},nQuality=1,},
		{szName="§»ng Long Ngäc H­ §¹o Hµnh ChØ Hoµn",tbProp={0,3174,},nQuality=1,},
		{szName="§»ng Long HuyÒn Thiªn BÊt DiÖt Ph¸p Giíi",tbProp={0,3184,},nQuality=1,},
		{szName="§»ng Long Ph­¬ng Nguyªn Cµn Kh«n Giíi",tbProp={0,3194,},nQuality=1,},
		{szName="§»ng Long Th­¬ng Khung D­¬ng Chi ChØ Hoµn",tbProp={0,3204,},nQuality=1,},
		{szName="§»ng Long Tè Du H¹ Giíi",tbProp={0,4822,},nQuality=1,},
		{szName="§»ng Long Y Thñy H¹ Giíi",tbProp={0,4832,},nQuality=1,},
	}
}


tbEquip_JinWuEx = 
{
		[1] = 
	{
		{szName="Kim ¤ CÈm Lan Ch©u Liªn",tbProp={0,2745,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam PhËt Ch©u",tbProp={0,2755,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc H¹ng Liªn",tbProp={0,2765,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Liªn",tbProp={0,2775,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m H¹ng Liªn",tbProp={0,2785,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt H¹ng Liªn",tbProp={0,2795,},nQuality=1,},
		{szName="Kim ¤ V« ý Ch©u Liªn",tbProp={0,2805,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Ch©u Liªn",tbProp={0,2815,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Ch©u Liªn",tbProp={0,2825,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Ch©u Liªn",tbProp={0,2835,},nQuality=1,},
		{szName="Kim ¤ U Minh H¹ng Liªn",tbProp={0,2845,},nQuality=1,},
		{szName="Kim ¤ Man §µ Ch©u Liªn",tbProp={0,2855,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh H¹ng Liªn",tbProp={0,2865,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c H¹ng Liªn",tbProp={0,2875,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch H¹ng Liªn",tbProp={0,2885,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt H¹ng Liªn",tbProp={0,2895,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt H¹ng Liªn",tbProp={0,2905,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong H¹ng Khuyªn",tbProp={0,2915,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt H¹ng Liªn",tbProp={0,2925,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Phï",tbProp={0,2935,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Phï",tbProp={0,2945,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh H¹ng Liªn",tbProp={0,2955,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Phï",tbProp={0,2965,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Phï",tbProp={0,4803,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Phï",tbProp={0,4793,},nQuality=1,},
	},
	[2] = 
	{
		{szName="Kim ¤ CÈm Lan T¨ng M¹o",tbProp={0,2746,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam T¨ng M¹o",tbProp={0,2756,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc T¨ng M¹o",tbProp={0,2766,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Kh«i",tbProp={0,2776,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Kh«i",tbProp={0,2786,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Kh«i",tbProp={0,2796,},nQuality=1,},
		{szName="Kim ¤ V« ý Ph¸t §¸i",tbProp={0,2806,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Ph¸t §¸i",tbProp={0,2816,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Tr©m",tbProp={0,2826,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Tr©m",tbProp={0,2836,},nQuality=1,},
		{szName="Kim ¤ U Minh Ph¸t §¸i",tbProp={0,2846,},nQuality=1,},
		{szName="Kim ¤ Man §µ Ph¸t §¸i",tbProp={0,2856,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Qu¸n",tbProp={0,2866,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Qu¸n",tbProp={0,2876,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Ph¸t Qu¸n",tbProp={0,2886,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt §Çu Hoµn",tbProp={0,2896,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt §Çu Hoµn",tbProp={0,2906,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Kh«i",tbProp={0,2916,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Qu¸n MiÖn",tbProp={0,2926,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Qu¸n",tbProp={0,2936,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Qu¸n",tbProp={0,2946,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh §¹o Qu¸n",tbProp={0,2956,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n §¹o Qu¸n",tbProp={0,2966,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n §¹o Qu¸n",tbProp={0,4804,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n §¹o Qu¸n",tbProp={0,4794,},nQuality=1,},
	},
	[3] = 
	{
		{szName="Kim ¤ CÈm Lan Th­îng Giíi",tbProp={0,2747,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam Th­îng Giíi",tbProp={0,2757,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc Th­îng Giíi",tbProp={0,2767,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Th­îng Giíi",tbProp={0,2777,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Th­îng Giíi",tbProp={0,2787,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Th­îng Giíi",tbProp={0,2797,},nQuality=1,},
		{szName="Kim ¤ V« ý Th­îng Giíi",tbProp={0,2807,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Th­îng Giíi",tbProp={0,2817,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Th­îng Giíi",tbProp={0,2827,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Th­îng Giíi",tbProp={0,2837,},nQuality=1,},
		{szName="Kim ¤ U Minh Th­îng Giíi",tbProp={0,2847,},nQuality=1,},
		{szName="Kim ¤ Man §µ Th­îng Giíi",tbProp={0,2857,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Th­îng Giíi",tbProp={0,2867,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Th­îng Giíi",tbProp={0,2877,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Th­îng Giíi",tbProp={0,2887,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt Th­îng Giíi",tbProp={0,2897,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt Th­îng Giíi",tbProp={0,2907,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Th­îng Giíi",tbProp={0,2917,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Th­îng Giíi",tbProp={0,2927,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Th­îng Giíi",tbProp={0,2937,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Th­îng Giíi",tbProp={0,2947,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh Th­îng Giíi",tbProp={0,2957,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Th­îng Giíi",tbProp={0,2967,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Th­îng Giíi",tbProp={0,4805,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Th­îng Giíi",tbProp={0,4795,},nQuality=1,},
	},
	[4] =
	{
		{szName="Kim ¤ CÈm Lan Hé UyÓn",tbProp={0,2748,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam Hé UyÓn",tbProp={0,2758,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc Hé UyÓn",tbProp={0,2768,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Thóc UyÓn",tbProp={0,2778,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Thóc UyÓn",tbProp={0,2788,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Thóc UyÓn",tbProp={0,2798,},nQuality=1,},
		{szName="Kim ¤ V« ý Hé UyÓn",tbProp={0,2808,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Hé UyÓn",tbProp={0,2818,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Tô",tbProp={0,2828,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Tô",tbProp={0,2838,},nQuality=1,},
		{szName="Kim ¤ U Minh Hé UyÓn",tbProp={0,2848,},nQuality=1,},
		{szName="Kim ¤ Man §µ Hé UyÓn",tbProp={0,2858,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Hé UyÓn",tbProp={0,2868,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Hé UyÓn",tbProp={0,2878,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Hé UyÓn",tbProp={0,2888,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt Hé UyÓn",tbProp={0,2898,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt Hé UyÓn",tbProp={0,2908,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Hé UyÓn",tbProp={0,2918,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Hé UyÓn",tbProp={0,2928,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Tô",tbProp={0,2938,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Tô",tbProp={0,2948,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh Hé UyÓn",tbProp={0,2958,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Hé UyÓn",tbProp={0,2968,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Hé UyÓn",tbProp={0,4806,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Hé UyÓn",tbProp={0,4796,},nQuality=1,},
	},
	[5] =
	{
		{szName="Kim ¤ CÈm Lan Yªu §¸i",tbProp={0,2749,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam Yªu §¸i",tbProp={0,2759,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc Yªu §¸i",tbProp={0,2769,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Yªu §¸i",tbProp={0,2779,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Yªu §¸i",tbProp={0,2789,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Yªu §¸i",tbProp={0,2799,},nQuality=1,},
		{szName="Kim ¤ V« ý Thóc Yªu",tbProp={0,2809,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Thóc Yªu",tbProp={0,2819,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Thóc Yªu",tbProp={0,2829,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Yªu §¸i",tbProp={0,2839,},nQuality=1,},
		{szName="Kim ¤ U Minh Yªu §¸i",tbProp={0,2849,},nQuality=1,},
		{szName="Kim ¤ Man §µ Yªu §¸i",tbProp={0,2859,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh TriÒn Yªu",tbProp={0,2869,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Thóc Yªu",tbProp={0,2879,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Thóc Yªu",tbProp={0,2889,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt Thóc Yªu",tbProp={0,2899,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt Thóc Yªu",tbProp={0,2909,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Yªu §¸i",tbProp={0,2919,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Yªu §¸i",tbProp={0,2929,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Ph¸p §¸i",tbProp={0,2939,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Ph¸p §¸i",tbProp={0,2949,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh Thóc Yªu",tbProp={0,2959,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n TriÒn Yªu",tbProp={0,2969,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n TriÒn Yªu",tbProp={0,4807,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n TriÒn Yªu",tbProp={0,4797,},nQuality=1,},
	},
	[6] = 
	{
		{szName="Kim ¤ CÈm Lan Cµ Sa",tbProp={0,2750,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam Cµ Sa",tbProp={0,2760,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc Cµ Sa",tbProp={0,2770,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Kh¶i",tbProp={0,2780,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Kh¶i",tbProp={0,2790,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Kh¶i",tbProp={0,2800,},nQuality=1,},
		{szName="Kim ¤ V« ý Sa Y",tbProp={0,2810,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Sam",tbProp={0,2820,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Sam",tbProp={0,2830,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Sam",tbProp={0,2840,},nQuality=1,},
		{szName="Kim ¤ U Minh Cèt Y",tbProp={0,2850,},nQuality=1,},
		{szName="Kim ¤ Man §µ BÝ Trang",tbProp={0,2860,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Gi¸p Y",tbProp={0,2870,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Gi¸p Y",tbProp={0,2880,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Gi¸p Y",tbProp={0,2890,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt C¸i Y",tbProp={0,2900,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt C¸i Y",tbProp={0,2910,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Gi¸p Y",tbProp={0,2920,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Gi¸p",tbProp={0,2930,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp §¹o Bµo",tbProp={0,2940,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa §¹o Bµo",tbProp={0,2950,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh §¹o Bµo",tbProp={0,2960,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n §¹o Bµo",tbProp={0,2970,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n §¹o Bµo",tbProp={0,4808,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n §¹o Bµo",tbProp={0,4798,},nQuality=1,},
	},
	[7] = 
	{
		{szName="Kim ¤ CÈm Lan TriÒn Thñ",tbProp={0,2751,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam T¨ng C«n",tbProp={0,2761,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc Giíi §ao",tbProp={0,2771,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Chïy",tbProp={0,2781,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Th­¬ng",tbProp={0,2791,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt B¶o §ao",tbProp={0,2801,},nQuality=1,},
		{szName="Kim ¤ V« ý Tr­êng KiÕm",tbProp={0,2811,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng TriÒn Thñ",tbProp={0,2821,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng §ao",tbProp={0,2831,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Uyªn ¦¬ng §ao",tbProp={0,2841,},nQuality=1,},		
		{szName="Kim ¤ U Minh TriÒn Thñ",tbProp={0,2851,},nQuality=1,},		
		{szName="Kim ¤ Man §µ La §ao",tbProp={0,2861,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Phi §ao",tbProp={0,2871,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c TiÔn",tbProp={0,2881,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Tiªu",tbProp={0,2891,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt TriÒn Thñ",tbProp={0,2901,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt Tr­îng",tbProp={0,2911,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Th­¬ng",tbProp={0,2921,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt §ao",tbProp={0,2931,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp KiÕm",tbProp={0,2941,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa KiÕm",tbProp={0,2951,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh B¶o §ao",tbProp={0,2961,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n B¶o KiÕm",tbProp={0,2971,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n B¶o KiÕm",tbProp={0,4809,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n B¶o KiÕm",tbProp={0,4799,},nQuality=1,},
	},
	[8] = 
	{
		{szName="Kim ¤ CÈm Lan T¨ng Hµi",tbProp={0,2752,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam T¨ng Hµi",tbProp={0,2762,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc T¨ng Hµi",tbProp={0,2772,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Ngoa",tbProp={0,2782,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Ngoa",tbProp={0,2792,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Ngoa",tbProp={0,2802,},nQuality=1,},
		{szName="Kim ¤ V« ý ?Ngoa",tbProp={0,2812,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Ngoa",tbProp={0,2822,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Ngoa",tbProp={0,2832,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Ngoa",tbProp={0,2842,},nQuality=1,},
		{szName="Kim ¤ U Minh Ngoa",tbProp={0,2852,},nQuality=1,},
		{szName="Kim ¤ Man §µ Ngoa",tbProp={0,2862,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Lý",tbProp={0,2872,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Lý",tbProp={0,2882,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Lý",tbProp={0,2892,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt Ngoa",tbProp={0,2902,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt Ngoa",tbProp={0,2912,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Ngoa",tbProp={0,2922,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Ngoa",tbProp={0,2932,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Lý",tbProp={0,2942,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Lý",tbProp={0,2952,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh Ngoa",tbProp={0,2962,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Ngoa",tbProp={0,2972,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Ngoa",tbProp={0,4810,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Ngoa",tbProp={0,4800,},nQuality=1,},
	},
	[9] = 
	{
		{szName="Kim ¤ CÈm Lan Yªu Trôy",tbProp={0,2753,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam Yªu Trôy",tbProp={0,2763,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc Yªu Trôy",tbProp={0,2773,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Béi",tbProp={0,2783,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Yªu Trôy",tbProp={0,2793,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Yªu Trôy",tbProp={0,2803,},nQuality=1,},
		{szName="Kim ¤ V« ý H­¬ng Nang",tbProp={0,2813,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng H­¬ng Nang",tbProp={0,2823,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng H­¬ng Nang",tbProp={0,2833,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c H­¬ng Nang",tbProp={0,2843,},nQuality=1,},
		{szName="Kim ¤ U Minh Yªu Trôy",tbProp={0,2853,},nQuality=1,},
		{szName="Kim ¤ Man §µ Yªu Trôy",tbProp={0,2863,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Béi",tbProp={0,2873,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Trôy",tbProp={0,2883,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Yªu Trôy",tbProp={0,2893,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt Yªu Trôy",tbProp={0,2903,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt Yªu Trôy",tbProp={0,2913,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Béi",tbProp={0,2923,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Béi",tbProp={0,2933,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Ngäc Béi",tbProp={0,2943,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Ngäc Béi",tbProp={0,2953,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh Béi",tbProp={0,2963,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Béi",tbProp={0,2973,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Béi",tbProp={0,4811,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Béi",tbProp={0,4801,},nQuality=1,},
	},
	[10] = 
	{
		{szName="Kim ¤ CÈm Lan H¹ Giíi",tbProp={0,2754,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam H¹ Giíi",tbProp={0,2764,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc H¹ Giíi",tbProp={0,2774,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c H¹ Giíi",tbProp={0,2784,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m H¹ Giíi",tbProp={0,2794,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt H¹ Giíi",tbProp={0,2804,},nQuality=1,},
		{szName="Kim ¤ V« ý H¹ Giíi",tbProp={0,2814,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng H¹ Giíi",tbProp={0,2824,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng H¹ Giíi",tbProp={0,2834,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c H¹ Giíi",tbProp={0,2844,},nQuality=1,},
		{szName="Kim ¤ U Minh H¹ Giíi",tbProp={0,2854,},nQuality=1,},
		{szName="Kim ¤ Man §µ H¹ Giíi",tbProp={0,2864,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh H¹ Giíi",tbProp={0,2874,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c H¹ Giíi",tbProp={0,2884,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch H¹ Giíi",tbProp={0,2894,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt H¹ Giíi",tbProp={0,2904,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt H¹ Giíi",tbProp={0,2914,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong H¹ Giíi",tbProp={0,2924,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt H¹ Giíi",tbProp={0,2934,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp H¹ Giíi",tbProp={0,2944,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa H¹ Giíi",tbProp={0,2954,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh H¹ Giíi",tbProp={0,2964,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n H¹ Giíi",tbProp={0,2974,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n H¹ Giíi",tbProp={0,4812,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n H¹ Giíi",tbProp={0,4802,},nQuality=1,},	},
}