tbEquip_jinwu = 
{
	[1] = 
	{
		{szName="Kim ¤ CÈm Lan Ch©u Liªn",tbProp={0,2745,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam PhËt Ch©u",tbProp={0,2755,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc H¹ng Liªn",tbProp={0,2765,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Liªn",tbProp={0,2775,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m H¹ng Liªn",tbProp={0,2785,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt H¹ng Liªn",tbProp={0,2795,},nQuality=1,},
		{szName="Kim ¤ V« ý Ch©u Liªn",tbProp={0,2805,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Ch©u Liªn",tbProp={0,2815,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Ch©u Liªn",tbProp={0,2825,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Ch©u Liªn",tbProp={0,2835,},nQuality=1,},
		{szName="Kim ¤ U Minh H¹ng Liªn",tbProp={0,2845,},nQuality=1,},
		{szName="Kim ¤ Man §µ Ch©u Liªn",tbProp={0,2855,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh H¹ng Liªn",tbProp={0,2865,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c H¹ng Liªn",tbProp={0,2875,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch H¹ng Liªn",tbProp={0,2885,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt H¹ng Liªn",tbProp={0,2895,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt H¹ng Liªn",tbProp={0,2905,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong H¹ng Khuyªn",tbProp={0,2915,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt H¹ng Liªn",tbProp={0,2925,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Phï",tbProp={0,2935,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Phï",tbProp={0,2945,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh H¹ng Liªn",tbProp={0,2955,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Phï",tbProp={0,2965,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Phï",tbProp={0,4803,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Phï",tbProp={0,4793,},nQuality=1,},
	},
	[2] = 
	{
		{szName="Kim ¤ CÈm Lan T¨ng M¹o",tbProp={0,2746,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam T¨ng M¹o",tbProp={0,2756,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc T¨ng M¹o",tbProp={0,2766,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Kh«i",tbProp={0,2776,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Kh«i",tbProp={0,2786,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Kh«i",tbProp={0,2796,},nQuality=1,},
		{szName="Kim ¤ V« ý Ph¸t §¸i",tbProp={0,2806,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Ph¸t §¸i",tbProp={0,2816,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Tr©m",tbProp={0,2826,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Tr©m",tbProp={0,2836,},nQuality=1,},
		{szName="Kim ¤ U Minh Ph¸t §¸i",tbProp={0,2846,},nQuality=1,},
		{szName="Kim ¤ Man §µ Ph¸t §¸i",tbProp={0,2856,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Qu¸n",tbProp={0,2866,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Qu¸n",tbProp={0,2876,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Ph¸t Qu¸n",tbProp={0,2886,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt §Çu Hoµn",tbProp={0,2896,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt §Çu Hoµn",tbProp={0,2906,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Kh«i",tbProp={0,2916,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Qu¸n MiÖn",tbProp={0,2926,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Qu¸n",tbProp={0,2936,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Qu¸n",tbProp={0,2946,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh §¹o Qu¸n",tbProp={0,2956,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n §¹o Qu¸n",tbProp={0,2966,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n §¹o Qu¸n",tbProp={0,4804,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n §¹o Qu¸n",tbProp={0,4794,},nQuality=1,},
	},
	[3] = 
	{
		{szName="Kim ¤ CÈm Lan Th­îng Giíi",tbProp={0,2747,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam Th­îng Giíi",tbProp={0,2757,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc Th­îng Giíi",tbProp={0,2767,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Th­îng Giíi",tbProp={0,2777,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Th­îng Giíi",tbProp={0,2787,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Th­îng Giíi",tbProp={0,2797,},nQuality=1,},
		{szName="Kim ¤ V« ý Th­îng Giíi",tbProp={0,2807,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Th­îng Giíi",tbProp={0,2817,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Th­îng Giíi",tbProp={0,2827,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Th­îng Giíi",tbProp={0,2837,},nQuality=1,},
		{szName="Kim ¤ U Minh Th­îng Giíi",tbProp={0,2847,},nQuality=1,},
		{szName="Kim ¤ Man §µ Th­îng Giíi",tbProp={0,2857,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Th­îng Giíi",tbProp={0,2867,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Th­îng Giíi",tbProp={0,2877,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Th­îng Giíi",tbProp={0,2887,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt Th­îng Giíi",tbProp={0,2897,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt Th­îng Giíi",tbProp={0,2907,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Th­îng Giíi",tbProp={0,2917,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Th­îng Giíi",tbProp={0,2927,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Th­îng Giíi",tbProp={0,2937,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Th­îng Giíi",tbProp={0,2947,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh Th­îng Giíi",tbProp={0,2957,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Th­îng Giíi",tbProp={0,2967,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Th­îng Giíi",tbProp={0,4805,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Th­îng Giíi",tbProp={0,4795,},nQuality=1,},
	},
	[4] =
	{
		{szName="Kim ¤ CÈm Lan Hé UyÓn",tbProp={0,2748,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam Hé UyÓn",tbProp={0,2758,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc Hé UyÓn",tbProp={0,2768,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Thóc UyÓn",tbProp={0,2778,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Thóc UyÓn",tbProp={0,2788,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Thóc UyÓn",tbProp={0,2798,},nQuality=1,},
		{szName="Kim ¤ V« ý Hé UyÓn",tbProp={0,2808,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Hé UyÓn",tbProp={0,2818,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Tô",tbProp={0,2828,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Tô",tbProp={0,2838,},nQuality=1,},
		{szName="Kim ¤ U Minh Hé UyÓn",tbProp={0,2848,},nQuality=1,},
		{szName="Kim ¤ Man §µ Hé UyÓn",tbProp={0,2858,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Hé UyÓn",tbProp={0,2868,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Hé UyÓn",tbProp={0,2878,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Hé UyÓn",tbProp={0,2888,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt Hé UyÓn",tbProp={0,2898,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt Hé UyÓn",tbProp={0,2908,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Hé UyÓn",tbProp={0,2918,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Hé UyÓn",tbProp={0,2928,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Tô",tbProp={0,2938,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Tô",tbProp={0,2948,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh Hé UyÓn",tbProp={0,2958,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Hé UyÓn",tbProp={0,2968,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Hé UyÓn",tbProp={0,4806,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Hé UyÓn",tbProp={0,4796,},nQuality=1,},
	},
	[5] =
	{
		{szName="Kim ¤ CÈm Lan Yªu §¸i",tbProp={0,2749,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam Yªu §¸i",tbProp={0,2759,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc Yªu §¸i",tbProp={0,2769,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Yªu §¸i",tbProp={0,2779,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Yªu §¸i",tbProp={0,2789,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Yªu §¸i",tbProp={0,2799,},nQuality=1,},
		{szName="Kim ¤ V« ý Thóc Yªu",tbProp={0,2809,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Thóc Yªu",tbProp={0,2819,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Thóc Yªu",tbProp={0,2829,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Yªu §¸i",tbProp={0,2839,},nQuality=1,},
		{szName="Kim ¤ U Minh Yªu §¸i",tbProp={0,2849,},nQuality=1,},
		{szName="Kim ¤ Man §µ Yªu §¸i",tbProp={0,2859,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh TriÒn Yªu",tbProp={0,2869,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Thóc Yªu",tbProp={0,2879,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Thóc Yªu",tbProp={0,2889,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt Thóc Yªu",tbProp={0,2899,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt Thóc Yªu",tbProp={0,2909,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Yªu §¸i",tbProp={0,2919,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Yªu §¸i",tbProp={0,2929,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Ph¸p §¸i",tbProp={0,2939,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Ph¸p §¸i",tbProp={0,2949,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh Thóc Yªu",tbProp={0,2959,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n TriÒn Yªu",tbProp={0,2969,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n TriÒn Yªu",tbProp={0,4807,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n TriÒn Yªu",tbProp={0,4797,},nQuality=1,},
	},
	[6] = 
	{
		{szName="Kim ¤ CÈm Lan Cµ Sa",tbProp={0,2750,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam Cµ Sa",tbProp={0,2760,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc Cµ Sa",tbProp={0,2770,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Kh¶i",tbProp={0,2780,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Kh¶i",tbProp={0,2790,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Kh¶i",tbProp={0,2800,},nQuality=1,},
		{szName="Kim ¤ V« ý Sa Y",tbProp={0,2810,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Sam",tbProp={0,2820,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Sam",tbProp={0,2830,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Sam",tbProp={0,2840,},nQuality=1,},
		{szName="Kim ¤ U Minh Cèt Y",tbProp={0,2850,},nQuality=1,},
		{szName="Kim ¤ Man §µ BÝ Trang",tbProp={0,2860,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Gi¸p Y",tbProp={0,2870,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Gi¸p Y",tbProp={0,2880,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Gi¸p Y",tbProp={0,2890,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt C¸i Y",tbProp={0,2900,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt C¸i Y",tbProp={0,2910,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Gi¸p Y",tbProp={0,2920,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Gi¸p",tbProp={0,2930,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp §¹o Bµo",tbProp={0,2940,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa §¹o Bµo",tbProp={0,2950,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh §¹o Bµo",tbProp={0,2960,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n §¹o Bµo",tbProp={0,2970,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n §¹o Bµo",tbProp={0,4808,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n §¹o Bµo",tbProp={0,4798,},nQuality=1,},
	},
	[7] = 
	{
		{szName="Kim ¤ CÈm Lan TriÒn Thñ",tbProp={0,2751,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam T¨ng C«n",tbProp={0,2761,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc Giíi §ao",tbProp={0,2771,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Chïy",tbProp={0,2781,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Th­¬ng",tbProp={0,2791,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt B¶o §ao",tbProp={0,2801,},nQuality=1,},
		{szName="Kim ¤ V« ý Tr­êng KiÕm",tbProp={0,2811,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng TriÒn Thñ",tbProp={0,2821,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng §ao",tbProp={0,2831,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Uyªn ¦¬ng §ao",tbProp={0,2841,},nQuality=1,},		
		{szName="Kim ¤ U Minh TriÒn Thñ",tbProp={0,2851,},nQuality=1,},		
		{szName="Kim ¤ Man §µ La §ao",tbProp={0,2861,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Phi §ao",tbProp={0,2871,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c TiÔn",tbProp={0,2881,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Tiªu",tbProp={0,2891,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt TriÒn Thñ",tbProp={0,2901,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt Tr­îng",tbProp={0,2911,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Th­¬ng",tbProp={0,2921,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt §ao",tbProp={0,2931,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp KiÕm",tbProp={0,2941,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa KiÕm",tbProp={0,2951,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh B¶o §ao",tbProp={0,2961,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n B¶o KiÕm",tbProp={0,2971,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n B¶o KiÕm",tbProp={0,4809,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n B¶o KiÕm",tbProp={0,4799,},nQuality=1,},
	},
	[8] = 
	{
		{szName="Kim ¤ CÈm Lan T¨ng Hµi",tbProp={0,2752,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam T¨ng Hµi",tbProp={0,2762,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc T¨ng Hµi",tbProp={0,2772,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Ngoa",tbProp={0,2782,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Ngoa",tbProp={0,2792,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Ngoa",tbProp={0,2802,},nQuality=1,},
		{szName="Kim ¤ V« ý ?Ngoa",tbProp={0,2812,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng Ngoa",tbProp={0,2822,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng Ngoa",tbProp={0,2832,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c Ngoa",tbProp={0,2842,},nQuality=1,},
		{szName="Kim ¤ U Minh Ngoa",tbProp={0,2852,},nQuality=1,},
		{szName="Kim ¤ Man §µ Ngoa",tbProp={0,2862,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Lý",tbProp={0,2872,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Lý",tbProp={0,2882,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Lý",tbProp={0,2892,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt Ngoa",tbProp={0,2902,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt Ngoa",tbProp={0,2912,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Ngoa",tbProp={0,2922,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Ngoa",tbProp={0,2932,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Lý",tbProp={0,2942,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Lý",tbProp={0,2952,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh Ngoa",tbProp={0,2962,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Ngoa",tbProp={0,2972,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Ngoa",tbProp={0,4810,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Ngoa",tbProp={0,4800,},nQuality=1,},
	},
	[9] = 
	{
		{szName="Kim ¤ CÈm Lan Yªu Trôy",tbProp={0,2753,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam Yªu Trôy",tbProp={0,2763,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc Yªu Trôy",tbProp={0,2773,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c Béi",tbProp={0,2783,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m Yªu Trôy",tbProp={0,2793,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt Yªu Trôy",tbProp={0,2803,},nQuality=1,},
		{szName="Kim ¤ V« ý H­¬ng Nang",tbProp={0,2813,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng H­¬ng Nang",tbProp={0,2823,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng H­¬ng Nang",tbProp={0,2833,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c H­¬ng Nang",tbProp={0,2843,},nQuality=1,},
		{szName="Kim ¤ U Minh Yªu Trôy",tbProp={0,2853,},nQuality=1,},
		{szName="Kim ¤ Man §µ Yªu Trôy",tbProp={0,2863,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh Béi",tbProp={0,2873,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c Trôy",tbProp={0,2883,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch Yªu Trôy",tbProp={0,2893,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt Yªu Trôy",tbProp={0,2903,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt Yªu Trôy",tbProp={0,2913,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong Béi",tbProp={0,2923,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt Béi",tbProp={0,2933,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp Ngäc Béi",tbProp={0,2943,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa Ngäc Béi",tbProp={0,2953,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh Béi",tbProp={0,2963,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Béi",tbProp={0,2973,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Béi",tbProp={0,4811,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n Béi",tbProp={0,4801,},nQuality=1,},
	},
	[10] = 
	{
		{szName="Kim ¤ CÈm Lan H¹ Giíi",tbProp={0,2754,},nQuality=1,},
		{szName="Kim ¤ Giµ Lam H¹ Giíi",tbProp={0,2764,},nQuality=1,},
		{szName="Kim ¤ Bµn Nh­îc H¹ Giíi",tbProp={0,2774,},nQuality=1,},
		{szName="Kim ¤ ChÊn Nh¹c H¹ Giíi",tbProp={0,2784,},nQuality=1,},
		{szName="Kim ¤ ChiÕu §¶m H¹ Giíi",tbProp={0,2794,},nQuality=1,},
		{szName="Kim ¤ LÞch HuyÕt H¹ Giíi",tbProp={0,2804,},nQuality=1,},
		{szName="Kim ¤ V« ý H¹ Giíi",tbProp={0,2814,},nQuality=1,},
		{szName="Kim ¤ Ng­ng S­¬ng H¹ Giíi",tbProp={0,2824,},nQuality=1,},
		{szName="Kim ¤ §inh H­¬ng H¹ Giíi",tbProp={0,2834,},nQuality=1,},
		{szName="Kim ¤ Anh L¹c H¹ Giíi",tbProp={0,2844,},nQuality=1,},
		{szName="Kim ¤ U Minh H¹ Giíi",tbProp={0,2854,},nQuality=1,},
		{szName="Kim ¤ Man §µ H¹ Giíi",tbProp={0,2864,},nQuality=1,},
		{szName="Kim ¤ TuyÖt T×nh H¹ Giíi",tbProp={0,2874,},nQuality=1,},
		{szName="Kim ¤ BÝch L¹c H¹ Giíi",tbProp={0,2884,},nQuality=1,},
		{szName="Kim ¤ TÞch LÞch H¹ Giíi",tbProp={0,2894,},nQuality=1,},
		{szName="Kim ¤ ThiÕt Cèt H¹ Giíi",tbProp={0,2904,},nQuality=1,},
		{szName="Kim ¤ Long HuyÕt H¹ Giíi",tbProp={0,2914,},nQuality=1,},
		{szName="Kim ¤ D¹ng Phong H¹ Giíi",tbProp={0,2924,},nQuality=1,},
		{szName="Kim ¤ ¸nh HuyÕt H¹ Giíi",tbProp={0,2934,},nQuality=1,},
		{szName="Kim ¤ Lôc Hîp H¹ Giíi",tbProp={0,2944,},nQuality=1,},
		{szName="Kim ¤ Th¸i Hßa H¹ Giíi",tbProp={0,2954,},nQuality=1,},
		{szName="Kim ¤ NguyÖt ¶nh H¹ Giíi",tbProp={0,2964,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n H¹ Giíi",tbProp={0,2974,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n H¹ Giíi",tbProp={0,4812,},nQuality=1,},
		{szName="Kim ¤ T­êng V©n H¹ Giíi",tbProp={0,4802,},nQuality=1,},
	},
}


tbRepresentName = 
{
	[1] = "QuyÒn ThiÕu L©m",
	[2] = "C«n ThiÕu L©m",
	[3] = "ThiÕu L©m ®ao",
	[4] = "Chïy Thiªn V­¬ng",
	[5] = "Th­¬ng Thiªn V­¬ng",
	[6] = "§ao Thiªn V­¬ng",
	[7] = "Nga Mi kiÕm",
	[8] = "Nga Mi ch­ëng",
	[9] = "Thóy Yªn ®ao",
	[10] = "ThiÕu Yªn néi",
	[11] = "Ngò §éc ch­ëng",
	[12] = "Ngò §éc ®ao",
	[13] = "§­êng M«n phi ®ao",
	[14] = "§­êng M«n ná",
	[15] = "§­êng M«n tiÓu",
	[16] = "C¸i Bang ch­ëng",
	[17] = "C¸i Bang c«n",
	[18] = "Thiªn NhÉn chiÕn",
	[19] = "Thiªn NhÉn ma",
	[20] = "Vâ §ang khÝ",
	[21] = "Vâ §ang kiÕm",
	[22] = "§ao C«n L«n",
	[23] = "KiÕm C«n L«n",
	[24] = "Hoa S¬n KiÕm",
	[25] = "Hoa S¬n KhÝ",
}